// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.operations;

import io.github.primelib.webmethodsapigateway4j.models.ServiceMgmtInputServiceRegistryUnpublish;
import java.util.Objects;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;
import org.jspecify.annotations.NonNull;

/**
 * UnpublishFromServiceRegistry
 * <p>
 * Unpublish one or more APIs from one or more service registries
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@Generated(value = "io.github.primelib.primecodegen")
public class UnpublishFromServiceRegistryOperationSpec {
    /**
     * allows to disable validation of the spec, use with care!
     */
    @ApiStatus.Experimental
    public static Boolean VALIDATION_ENABLED = true;

    /**
     * Service registry unpublish payload
     *
     */
    @NonNull
    private ServiceMgmtInputServiceRegistryUnpublish payload;

    /**
     * Constructs a validated instance of {@link UnpublishFromServiceRegistryOperationSpec}.
     *
     * @param spec the specification to process
     */
    @ApiStatus.Internal
    public UnpublishFromServiceRegistryOperationSpec(Consumer<UnpublishFromServiceRegistryOperationSpec> spec) {
        spec.accept(this);
        if (VALIDATION_ENABLED)
            validate();
    }

    /**
     * Validates the Spec, will throw a exception if required parameters are missing
     *
     * @throws NullPointerException
     */
    public void validate() {
        Objects.requireNonNull(payload, "payload is a required parameter!");
    }
}
