// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.enums;

import com.fasterxml.jackson.annotation.JsonTypeName;
import javax.annotation.processing.Generated;

/**
 * AlgorithmEnum
 * <p>
 * Type of algorithm that needs to be used for signing the JWT
 *
 */
@JsonTypeName("AlgorithmEnum")
@Generated(value = "io.github.primelib.primecodegen")
public enum AlgorithmEnum {
    RS_256("RS256"),
    RS_384("RS384"),
    RS_512("RS512"),
    ;

    private final String value;

    AlgorithmEnum(String value) {
        this.value = value;
    }
}
