// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.enums;

import com.fasterxml.jackson.annotation.JsonTypeName;
import javax.annotation.processing.Generated;

/**
 * AssertionTypeEnum
 * <p>
 * Type of assertion(tokenAssertion/bindingAssertion)
 *
 */
@JsonTypeName("AssertionTypeEnum")
@Generated(value = "io.github.primelib.primecodegen")
public enum AssertionTypeEnum {
    BINDING_ASSERTION("bindingAssertion"),
    POLICY_ASSERTION("policyAssertion"),
    TOKEN_ASSERTION("tokenAssertion"),
    ;

    private final String value;

    AssertionTypeEnum(String value) {
        this.value = value;
    }
}
