// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.enums;

import com.fasterxml.jackson.annotation.JsonTypeName;
import javax.annotation.processing.Generated;

/**
 * FilterTypeEnum
 * <p>
 * This property is used to define the type of filter we will be using to define attributes. The allowed values are apis, httpMethod, tags. If API type is specified we can specify the fields of API such as apiName, apiDescription, apiVersion. If httpMethod specified we can specify the httpMethods(GET/POST/PUT/DELETE/POST) of the resource to filter the resource. This filter type is used for REST APIs only. If tag type is specified we can specify the field tags in API to filter api using tags. This is also only applicable for REST APIs.
 *
 */
@JsonTypeName("FilterTypeEnum")
@Generated(value = "io.github.primelib.primecodegen")
public enum FilterTypeEnum {
    API("API"),
    HTTP_METHOD("HTTP_METHOD"),
    ;

    private final String value;

    FilterTypeEnum(String value) {
        this.value = value;
    }
}
