// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.enums;

import com.fasterxml.jackson.annotation.JsonTypeName;
import javax.annotation.processing.Generated;

/**
 * HttpMethodEnum
 * <p>
 * HttpMethod that is used while communicating with the service registry
 *
 */
@JsonTypeName("HttpMethodEnum")
@Generated(value = "io.github.primelib.primecodegen")
public enum HttpMethodEnum {
    CUSTOM("CUSTOM"),
    DELETE("DELETE"),
    GET("GET"),
    HEAD("HEAD"),
    OPTIONS("OPTIONS"),
    PATCH("PATCH"),
    POST("POST"),
    PUT("PUT"),
    TRACE("TRACE"),
    ;

    private final String value;

    HttpMethodEnum(String value) {
        this.value = value;
    }
}
