// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.enums;

import com.fasterxml.jackson.annotation.JsonTypeName;
import javax.annotation.processing.Generated;

/**
 * IsDefaultEnum
 * <p>
 * Indicates whether this proxy server alias is the default for the corresponding protocol. There can be only one default proxy server alias for a given protocol. Y denotes Yes and N denotes No.
 *
 */
@JsonTypeName("IsDefaultEnum")
@Generated(value = "io.github.primelib.primecodegen")
public enum IsDefaultEnum {
    N("N"),
    Y("Y"),
    ;

    private final String value;

    IsDefaultEnum(String value) {
        this.value = value;
    }
}
