// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.enums;

import com.fasterxml.jackson.annotation.JsonTypeName;
import javax.annotation.processing.Generated;

/**
 * LogicalConnectorEnum
 *
 */
@JsonTypeName("LogicalConnectorEnum")
@Generated(value = "io.github.primelib.primecodegen")
public enum LogicalConnectorEnum {
    AND("AND"),
    OR("OR"),
    ;

    private final String value;

    LogicalConnectorEnum(String value) {
        this.value = value;
    }
}
