// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.enums;

import com.fasterxml.jackson.annotation.JsonTypeName;
import javax.annotation.processing.Generated;

/**
 * OriginEnum
 *
 */
@JsonTypeName("OriginEnum")
@Generated(value = "io.github.primelib.primecodegen")
public enum OriginEnum {
    CLIENT("Client"),
    SERVER("Server"),
    ;

    private final String value;

    OriginEnum(String value) {
        this.value = value;
    }
}
