// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.enums;

import com.fasterxml.jackson.annotation.JsonTypeName;
import javax.annotation.processing.Generated;

/**
 * SortOrderEnum
 * <p>
 * Sort order for the records
 *
 */
@JsonTypeName("SortOrderEnum")
@Generated(value = "io.github.primelib.primecodegen")
public enum SortOrderEnum {
    ASC("ASC"),
    DESC("DESC"),
    ;

    private final String value;

    SortOrderEnum(String value) {
        this.value = value;
    }
}
