// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package operations

import (
	"context"
	"net/http"

	"github.com/go-resty/resty/v2"
	"github.com/primelib/primecodegen-lib-go/requeststruct"
	"github.com/primelib/webmethods-api-gateway-client/sdk/go/pkgs/models"
)

type ActivateApiRequest struct {
	APIId *string `pathParam:"style=simple,explode=false,name=apiId"` // API Id for the API to be activated
}

type ActivateApiResponse struct {
	// Success response
	Result *models.ServiceMgmtAPIResponse
	// Error response
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

// ActivateApi Activate an API so that API is exposed to consumers
//
//meta:operation PUT /apis/{apiId}/activate
func ActivateApi(client *resty.Client, ctx context.Context, req ActivateApiRequest) (*ActivateApiResponse, error) {
	r := client.R().SetContext(ctx)

	// process request parameters
	reqData, err := requeststruct.ResolveRequestParams(req)
	if err != nil {
		return nil, err
	}
	r.SetHeader("Accept", "application/json")
	r.SetHeaders(reqData.HeaderParams)
	r.SetPathParams(reqData.PathParams)
	r.SetQueryParamsFromValues(reqData.QueryParams)
	if reqData.BodyParam != nil {
		r.SetBody(reqData.BodyParam)
	}
	result := new(models.ServiceMgmtAPIResponse)
	r.SetResult(result)

	// send the request
	resp, err := r.Put("/apis/{apiId}/activate")
	if err != nil {
		return nil, err
	}

	return &ActivateApiResponse{
		StatusCode:  resp.StatusCode(),
		RawResponse: resp.RawResponse,
		Result:      result,
	}, nil
}
