// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package operations

import (
	"context"
	"net/http"

	"github.com/go-resty/resty/v2"
	"github.com/primelib/primecodegen-lib-go/requeststruct"
	"github.com/primelib/webmethods-api-gateway-client/sdk/go/pkgs/models"
)

type AuthorizeUserRequest struct {
	Payload *models.UserMgmtUser `bodyParam:""` // This parameter describes the request payload of a user that is to be created in API Gateway.
}

type AuthorizeUserResponse struct {
	// Success response
	Result *models.UserMgmtUser
	// Error response
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

// AuthorizeUser This HTTP request authenticates an User in API Gateway.
//
//meta:operation POST /users/authenticate
func AuthorizeUser(client *resty.Client, ctx context.Context, req AuthorizeUserRequest) (*AuthorizeUserResponse, error) {
	r := client.R().SetContext(ctx)

	// process request parameters
	reqData, err := requeststruct.ResolveRequestParams(req)
	if err != nil {
		return nil, err
	}
	r.SetHeader("Content-Type", "application/json")
	r.SetHeader("Accept", "application/json")
	r.SetHeaders(reqData.HeaderParams)
	r.SetPathParams(reqData.PathParams)
	r.SetQueryParamsFromValues(reqData.QueryParams)
	if reqData.BodyParam != nil {
		r.SetBody(reqData.BodyParam)
	}
	result := new(models.UserMgmtUser)
	r.SetResult(result)

	// send the request
	resp, err := r.Post("/users/authenticate")
	if err != nil {
		return nil, err
	}

	return &AuthorizeUserResponse{
		StatusCode:  resp.StatusCode(),
		RawResponse: resp.RawResponse,
		Result:      result,
	}, nil
}
