// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package operations

import (
	"context"
	"net/http"

	"github.com/go-resty/resty/v2"
	"github.com/primelib/primecodegen-lib-go/requeststruct"
)

type DeleteControlPlaneConfigurationRequest struct {
}

type DeleteControlPlaneConfigurationResponse struct {
	// Error response
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

// DeleteControlPlaneConfiguration This API allows you to delete an API Control Plane agent configuration in API Gateway.
//
//meta:operation DELETE /controlplane/config
func DeleteControlPlaneConfiguration(client *resty.Client, ctx context.Context, req DeleteControlPlaneConfigurationRequest) (*DeleteControlPlaneConfigurationResponse, error) {
	r := client.R().SetContext(ctx)

	// process request parameters
	reqData, err := requeststruct.ResolveRequestParams(req)
	if err != nil {
		return nil, err
	}
	r.SetHeaders(reqData.HeaderParams)
	r.SetPathParams(reqData.PathParams)
	r.SetQueryParamsFromValues(reqData.QueryParams)
	if reqData.BodyParam != nil {
		r.SetBody(reqData.BodyParam)
	}

	// send the request
	resp, err := r.Delete("/controlplane/config")
	if err != nil {
		return nil, err
	}

	return &DeleteControlPlaneConfigurationResponse{
		StatusCode:  resp.StatusCode(),
		RawResponse: resp.RawResponse,
	}, nil
}
