// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package operations

import (
	"context"
	"net/http"

	"github.com/go-resty/resty/v2"
	"github.com/primelib/primecodegen-lib-go/requeststruct"
)

type EnableOutboundProxyRequest struct {
	OutboundproxyAlias *string `pathParam:"style=simple,explode=false,name=outboundproxyAlias"` // The outbound proxy server alias to be enabled
}

type EnableOutboundProxyResponse struct {
	// Error response
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

// EnableOutboundProxy Enables an already existing outbound proxy server alias in API Gateway.
//
//meta:operation PUT /is/outboundproxy{outboundproxyAlias}/enable
func EnableOutboundProxy(client *resty.Client, ctx context.Context, req EnableOutboundProxyRequest) (*EnableOutboundProxyResponse, error) {
	r := client.R().SetContext(ctx)

	// process request parameters
	reqData, err := requeststruct.ResolveRequestParams(req)
	if err != nil {
		return nil, err
	}
	r.SetHeaders(reqData.HeaderParams)
	r.SetPathParams(reqData.PathParams)
	r.SetQueryParamsFromValues(reqData.QueryParams)
	if reqData.BodyParam != nil {
		r.SetBody(reqData.BodyParam)
	}

	// send the request
	resp, err := r.Put("/is/outboundproxy{outboundproxyAlias}/enable")
	if err != nil {
		return nil, err
	}

	return &EnableOutboundProxyResponse{
		StatusCode:  resp.StatusCode(),
		RawResponse: resp.RawResponse,
	}, nil
}
