// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package operations

import (
	"context"
	"net/http"

	"github.com/go-resty/resty/v2"
	"github.com/primelib/primecodegen-lib-go/requeststruct"
	"github.com/primelib/webmethods-api-gateway-client/sdk/go/pkgs/models"
)

type GetJmsconnectionRequest struct {
	JmsConnId *string `pathParam:"style=simple,explode=false,name=jmsConnId"` // This path parameter is used to specify the JMS connection id which JMS connection needs to be retrived.
}

type GetJmsconnectionResponse struct {
	// Success response
	Result *models.AdminJmsconnectionAlias
	// Error response
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

// GetJmsconnection The method retrieves the specified JMS connection in API Gateway.
//
//meta:operation GET /is/jmsConnections/{jmsConnId}
func GetJmsconnection(client *resty.Client, ctx context.Context, req GetJmsconnectionRequest) (*GetJmsconnectionResponse, error) {
	r := client.R().SetContext(ctx)

	// process request parameters
	reqData, err := requeststruct.ResolveRequestParams(req)
	if err != nil {
		return nil, err
	}
	r.SetHeader("Accept", "application/json")
	r.SetHeaders(reqData.HeaderParams)
	r.SetPathParams(reqData.PathParams)
	r.SetQueryParamsFromValues(reqData.QueryParams)
	if reqData.BodyParam != nil {
		r.SetBody(reqData.BodyParam)
	}
	result := new(models.AdminJmsconnectionAlias)
	r.SetResult(result)

	// send the request
	resp, err := r.Get("/is/jmsConnections/{jmsConnId}")
	if err != nil {
		return nil, err
	}

	return &GetJmsconnectionResponse{
		StatusCode:  resp.StatusCode(),
		RawResponse: resp.RawResponse,
		Result:      result,
	}, nil
}
