// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package operations

import (
	"context"
	"net/http"

	"github.com/go-resty/resty/v2"
	"github.com/primelib/primecodegen-lib-go/requeststruct"
	"github.com/primelib/webmethods-api-gateway-client/sdk/go/pkgs/models"
)

type GetKeystoresRequest struct {
}

type GetKeystoresResponse struct {
	// Success response
	Result []*models.AdminKeyStore
	// Error response
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

// GetKeystores The method gets all keystores available in API Gateway.
//
//meta:operation GET /is/keystore
func GetKeystores(client *resty.Client, ctx context.Context, req GetKeystoresRequest) (*GetKeystoresResponse, error) {
	r := client.R().SetContext(ctx)

	// process request parameters
	reqData, err := requeststruct.ResolveRequestParams(req)
	if err != nil {
		return nil, err
	}
	r.SetHeader("Accept", "application/json")
	r.SetHeaders(reqData.HeaderParams)
	r.SetPathParams(reqData.PathParams)
	r.SetQueryParamsFromValues(reqData.QueryParams)
	if reqData.BodyParam != nil {
		r.SetBody(reqData.BodyParam)
	}
	var result []*models.AdminKeyStore
	r.SetResult(result)

	// send the request
	resp, err := r.Get("/is/keystore")
	if err != nil {
		return nil, err
	}

	return &GetKeystoresResponse{
		StatusCode:  resp.StatusCode(),
		RawResponse: resp.RawResponse,
	}, nil
}
