// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package operations

import (
	"context"
	"net/http"

	"github.com/go-resty/resty/v2"
	"github.com/primelib/primecodegen-lib-go/requeststruct"
	"github.com/primelib/webmethods-api-gateway-client/sdk/go/pkgs/models"
)

type GetOauthScopesRequest struct {
}

type GetOauthScopesResponse struct {
	// Success response
	Result *models.ServiceMgmtGatewayScope
	// Error response
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

// GetOauthScopes This method retrieves a list of available OAuth scope mappings in API Gateway. OAuth scope mappings map the authorization server scope with APIs or API scopes
//
//meta:operation GET /scopes
func GetOauthScopes(client *resty.Client, ctx context.Context, req GetOauthScopesRequest) (*GetOauthScopesResponse, error) {
	r := client.R().SetContext(ctx)

	// process request parameters
	reqData, err := requeststruct.ResolveRequestParams(req)
	if err != nil {
		return nil, err
	}
	r.SetHeader("Accept", "application/json")
	r.SetHeaders(reqData.HeaderParams)
	r.SetPathParams(reqData.PathParams)
	r.SetQueryParamsFromValues(reqData.QueryParams)
	if reqData.BodyParam != nil {
		r.SetBody(reqData.BodyParam)
	}
	result := new(models.ServiceMgmtGatewayScope)
	r.SetResult(result)

	// send the request
	resp, err := r.Get("/scopes")
	if err != nil {
		return nil, err
	}

	return &GetOauthScopesResponse{
		StatusCode:  resp.StatusCode(),
		RawResponse: resp.RawResponse,
		Result:      result,
	}, nil
}
