// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package operations

import (
	"context"
	"net/http"

	"github.com/go-resty/resty/v2"
	"github.com/primelib/primecodegen-lib-go/requeststruct"
	"github.com/primelib/webmethods-api-gateway-client/sdk/go/pkgs/models"
)

type GetPlansForPackageByIdRequest struct {
	PackageId *string `pathParam:"style=simple,explode=false,name=packageId"` // Id of the Package
}

type GetPlansForPackageByIdResponse struct {
	// Success response
	Result *models.MonetizationPackagePlansResponseContainer
	// Error response
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

// GetPlansForPackageById To get list of all plans associated to the given package id
//
//meta:operation GET /packages/{packageId}/plans
func GetPlansForPackageById(client *resty.Client, ctx context.Context, req GetPlansForPackageByIdRequest) (*GetPlansForPackageByIdResponse, error) {
	r := client.R().SetContext(ctx)

	// process request parameters
	reqData, err := requeststruct.ResolveRequestParams(req)
	if err != nil {
		return nil, err
	}
	r.SetHeader("Accept", "application/json")
	r.SetHeaders(reqData.HeaderParams)
	r.SetPathParams(reqData.PathParams)
	r.SetQueryParamsFromValues(reqData.QueryParams)
	if reqData.BodyParam != nil {
		r.SetBody(reqData.BodyParam)
	}
	result := new(models.MonetizationPackagePlansResponseContainer)
	r.SetResult(result)

	// send the request
	resp, err := r.Get("/packages/{packageId}/plans")
	if err != nil {
		return nil, err
	}

	return &GetPlansForPackageByIdResponse{
		StatusCode:  resp.StatusCode(),
		RawResponse: resp.RawResponse,
		Result:      result,
	}, nil
}
