// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package operations

import (
	"context"
	"net/http"

	"github.com/go-resty/resty/v2"
	"github.com/primelib/primecodegen-lib-go/requeststruct"
	"github.com/primelib/webmethods-api-gateway-client/sdk/go/pkgs/models"
)

type GetPortRequest struct {
	ListenerKey *string `pathParam:"style=simple,explode=false,name=listenerKey"` // The listenerKey parameter uniquely identifies a port configuration within the WmRoot package.
}

type GetPortResponse struct {
	// Success response
	Result *models.PortMgmtPort
	// Error response
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

// GetPort The GET method retrieves an API Gateway port configuration
//
//meta:operation GET /ports/{listenerKey}
func GetPort(client *resty.Client, ctx context.Context, req GetPortRequest) (*GetPortResponse, error) {
	r := client.R().SetContext(ctx)

	// process request parameters
	reqData, err := requeststruct.ResolveRequestParams(req)
	if err != nil {
		return nil, err
	}
	r.SetHeader("Accept", "application/json")
	r.SetHeaders(reqData.HeaderParams)
	r.SetPathParams(reqData.PathParams)
	r.SetQueryParamsFromValues(reqData.QueryParams)
	if reqData.BodyParam != nil {
		r.SetBody(reqData.BodyParam)
	}
	result := new(models.PortMgmtPort)
	r.SetResult(result)

	// send the request
	resp, err := r.Get("/ports/{listenerKey}")
	if err != nil {
		return nil, err
	}

	return &GetPortResponse{
		StatusCode:  resp.StatusCode(),
		RawResponse: resp.RawResponse,
		Result:      result,
	}, nil
}
