// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package operations

import (
	"context"
	"net/http"

	"github.com/go-resty/resty/v2"
	"github.com/primelib/primecodegen-lib-go/requeststruct"
	"github.com/primelib/webmethods-api-gateway-client/sdk/go/pkgs/models"
)

type GetRuleRequest struct {
	RuleId *string `pathParam:"style=simple,explode=false,name=ruleId"` // The path parameter specifies the id of a rule that is to be retrieved.
}

type GetRuleResponse struct {
	// Success response
	Result *models.AdminRule
	// Error response
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

// GetRule The method retrieves the details of a rule in API Gateway.
//
//meta:operation GET /rule/{ruleId}
func GetRule(client *resty.Client, ctx context.Context, req GetRuleRequest) (*GetRuleResponse, error) {
	r := client.R().SetContext(ctx)

	// process request parameters
	reqData, err := requeststruct.ResolveRequestParams(req)
	if err != nil {
		return nil, err
	}
	r.SetHeader("Accept", "application/json")
	r.SetHeaders(reqData.HeaderParams)
	r.SetPathParams(reqData.PathParams)
	r.SetQueryParamsFromValues(reqData.QueryParams)
	if reqData.BodyParam != nil {
		r.SetBody(reqData.BodyParam)
	}
	result := new(models.AdminRule)
	r.SetResult(result)

	// send the request
	resp, err := r.Get("/rule/{ruleId}")
	if err != nil {
		return nil, err
	}

	return &GetRuleResponse{
		StatusCode:  resp.StatusCode(),
		RawResponse: resp.RawResponse,
		Result:      result,
	}, nil
}
