// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package operations

import (
	"context"
	"net/http"

	"github.com/go-resty/resty/v2"
	"github.com/primelib/primecodegen-lib-go/requeststruct"
	"github.com/primelib/webmethods-api-gateway-client/sdk/go/pkgs/models"
)

type GetSubscriptionBySubscriptionIdRequest struct {
	ApplicationId *string `pathParam:"style=simple,explode=false,name=applicationId"` // Application id to view the details of the application
}

type GetSubscriptionBySubscriptionIdResponse struct {
	// Success response
	Result *models.MonetizationApplication
	// Error response
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

// GetSubscriptionBySubscriptionId This endpoint is used to fetch the application details of the subscription.
//
//meta:operation GET /subscriptions/{applicationId}
func GetSubscriptionBySubscriptionId(client *resty.Client, ctx context.Context, req GetSubscriptionBySubscriptionIdRequest) (*GetSubscriptionBySubscriptionIdResponse, error) {
	r := client.R().SetContext(ctx)

	// process request parameters
	reqData, err := requeststruct.ResolveRequestParams(req)
	if err != nil {
		return nil, err
	}
	r.SetHeader("Accept", "application/json")
	r.SetHeaders(reqData.HeaderParams)
	r.SetPathParams(reqData.PathParams)
	r.SetQueryParamsFromValues(reqData.QueryParams)
	if reqData.BodyParam != nil {
		r.SetBody(reqData.BodyParam)
	}
	result := new(models.MonetizationApplication)
	r.SetResult(result)

	// send the request
	resp, err := r.Get("/subscriptions/{applicationId}")
	if err != nil {
		return nil, err
	}

	return &GetSubscriptionBySubscriptionIdResponse{
		StatusCode:  resp.StatusCode(),
		RawResponse: resp.RawResponse,
		Result:      result,
	}, nil
}
