// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package operations

import (
	"context"
	"net/http"

	"github.com/go-resty/resty/v2"
	"github.com/primelib/primecodegen-lib-go/requeststruct"
	"github.com/primelib/webmethods-api-gateway-client/sdk/go/pkgs/models"
)

type GetServiceRegistryPublishInfoRequest struct {
	APIId *string `queryParam:"style=simple,explode=false,name=apiId"` // API Id of the API for which ServiceRegistryPublishInfo is to be fetched
}

type GetServiceRegistryPublishInfoResponse struct {
	// Success response
	Result *models.ServiceMgmtServiceRegistryPublishGetResponse
	// Error response
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

// GetServiceRegistryPublishInfo Retrieve the service registry publish information for the API
//
//meta:operation GET /serviceRegistry/publish
func GetServiceRegistryPublishInfo(client *resty.Client, ctx context.Context, req GetServiceRegistryPublishInfoRequest) (*GetServiceRegistryPublishInfoResponse, error) {
	r := client.R().SetContext(ctx)

	// process request parameters
	reqData, err := requeststruct.ResolveRequestParams(req)
	if err != nil {
		return nil, err
	}
	r.SetHeader("Accept", "application/json")
	r.SetHeaders(reqData.HeaderParams)
	r.SetPathParams(reqData.PathParams)
	r.SetQueryParamsFromValues(reqData.QueryParams)
	if reqData.BodyParam != nil {
		r.SetBody(reqData.BodyParam)
	}
	result := new(models.ServiceMgmtServiceRegistryPublishGetResponse)
	r.SetResult(result)

	// send the request
	resp, err := r.Get("/serviceRegistry/publish")
	if err != nil {
		return nil, err
	}

	return &GetServiceRegistryPublishInfoResponse{
		StatusCode:  resp.StatusCode(),
		RawResponse: resp.RawResponse,
		Result:      result,
	}, nil
}
