// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package operations

import (
	"context"
	"net/http"

	"github.com/go-resty/resty/v2"
	"github.com/primelib/primecodegen-lib-go/requeststruct"
	"github.com/primelib/webmethods-api-gateway-client/sdk/go/pkgs/models"
)

type PatchDocumentRequest struct {
	DocumentId *string                      `pathParam:"style=simple,explode=false,name=documentId"` // The unique identifier of the document to be patched.
	Payload    *models.DocumentMgmtDocument `bodyParam:""`                                           // The request payload to patch the document in API Gateway.
}

type PatchDocumentResponse struct {
	// Success response
	Result *models.DocumentMgmtDocumentResponse
	// Error response
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

// PatchDocument
//
//meta:operation PATCH /documents/{documentId}
func PatchDocument(client *resty.Client, ctx context.Context, req PatchDocumentRequest) (*PatchDocumentResponse, error) {
	r := client.R().SetContext(ctx)

	// process request parameters
	reqData, err := requeststruct.ResolveRequestParams(req)
	if err != nil {
		return nil, err
	}
	r.SetHeader("Content-Type", "application/json")
	r.SetHeader("Accept", "application/json")
	r.SetHeaders(reqData.HeaderParams)
	r.SetPathParams(reqData.PathParams)
	r.SetQueryParamsFromValues(reqData.QueryParams)
	if reqData.BodyParam != nil {
		r.SetBody(reqData.BodyParam)
	}
	result := new(models.DocumentMgmtDocumentResponse)
	r.SetResult(result)

	// send the request
	resp, err := r.Patch("/documents/{documentId}")
	if err != nil {
		return nil, err
	}

	return &PatchDocumentResponse{
		StatusCode:  resp.StatusCode(),
		RawResponse: resp.RawResponse,
		Result:      result,
	}, nil
}
