// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package operations

import (
	"context"
	"net/http"

	"github.com/go-resty/resty/v2"
	"github.com/primelib/primecodegen-lib-go/requeststruct"
	"github.com/primelib/webmethods-api-gateway-client/sdk/go/pkgs/models"
)

type PublishToIntegrationServerRequest struct {
	Payload *models.ServiceMgmtInputIntegrationServerPublish `bodyParam:""` // Integration server publish payload
}

type PublishToIntegrationServerResponse struct {
	// Success response
	Result *models.ServiceMgmtServiceRegistryPublishPutResponse
	// Error response
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

// PublishToIntegrationServer Publish one or more APIs to one or more integration servers. Only REST and SOAP APIs are supported.
//
//meta:operation PUT /integrationServer/publish
func PublishToIntegrationServer(client *resty.Client, ctx context.Context, req PublishToIntegrationServerRequest) (*PublishToIntegrationServerResponse, error) {
	r := client.R().SetContext(ctx)

	// process request parameters
	reqData, err := requeststruct.ResolveRequestParams(req)
	if err != nil {
		return nil, err
	}
	r.SetHeader("Content-Type", "application/json")
	r.SetHeader("Accept", "application/json")
	r.SetHeaders(reqData.HeaderParams)
	r.SetPathParams(reqData.PathParams)
	r.SetQueryParamsFromValues(reqData.QueryParams)
	if reqData.BodyParam != nil {
		r.SetBody(reqData.BodyParam)
	}
	result := new(models.ServiceMgmtServiceRegistryPublishPutResponse)
	r.SetResult(result)

	// send the request
	resp, err := r.Put("/integrationServer/publish")
	if err != nil {
		return nil, err
	}

	return &PublishToIntegrationServerResponse{
		StatusCode:  resp.StatusCode(),
		RawResponse: resp.RawResponse,
		Result:      result,
	}, nil
}
