// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package operations

import (
	"context"
	"net/http"

	"github.com/go-resty/resty/v2"
	"github.com/primelib/primecodegen-lib-go/requeststruct"
	"github.com/primelib/webmethods-api-gateway-client/sdk/go/pkgs/models"
)

type SaveCentraSiteCommunicationAsDestinationRequest struct {
	Payload *models.AdminCscommunicationDestination `bodyParam:""`
}

type SaveCentraSiteCommunicationAsDestinationResponse struct {
	// Success response
	Result *models.AdminCscommunicationDestination
	// Error response
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

// SaveCentraSiteCommunicationAsDestination The method is used to update the Communication details of the CentraSite destination in API Gateway.
//
//meta:operation PUT /configurations/centraSiteDestinationCommunicationConfig
func SaveCentraSiteCommunicationAsDestination(client *resty.Client, ctx context.Context, req SaveCentraSiteCommunicationAsDestinationRequest) (*SaveCentraSiteCommunicationAsDestinationResponse, error) {
	r := client.R().SetContext(ctx)

	// process request parameters
	reqData, err := requeststruct.ResolveRequestParams(req)
	if err != nil {
		return nil, err
	}
	r.SetHeader("Content-Type", "application/json")
	r.SetHeader("Accept", "application/json")
	r.SetHeaders(reqData.HeaderParams)
	r.SetPathParams(reqData.PathParams)
	r.SetQueryParamsFromValues(reqData.QueryParams)
	if reqData.BodyParam != nil {
		r.SetBody(reqData.BodyParam)
	}
	result := new(models.AdminCscommunicationDestination)
	r.SetResult(result)

	// send the request
	resp, err := r.Put("/configurations/centraSiteDestinationCommunicationConfig")
	if err != nil {
		return nil, err
	}

	return &SaveCentraSiteCommunicationAsDestinationResponse{
		StatusCode:  resp.StatusCode(),
		RawResponse: resp.RawResponse,
		Result:      result,
	}, nil
}
