// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package operations

import (
	"context"
	"net/http"

	"github.com/go-resty/resty/v2"
	"github.com/primelib/primecodegen-lib-go/requeststruct"
	"github.com/primelib/webmethods-api-gateway-client/sdk/go/pkgs/models"
)

type UnpublishFromServiceRegistryRequest struct {
	Payload *models.ServiceMgmtInputServiceRegistryUnpublish `bodyParam:""` // Service registry unpublish payload
}

type UnpublishFromServiceRegistryResponse struct {
	// Success response
	Result *models.ServiceMgmtServiceRegistryUnpublishPutResponse
	// Error response
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

// UnpublishFromServiceRegistry Unpublish one or more APIs from one or more service registries
//
//meta:operation PUT /serviceRegistry/unpublish
func UnpublishFromServiceRegistry(client *resty.Client, ctx context.Context, req UnpublishFromServiceRegistryRequest) (*UnpublishFromServiceRegistryResponse, error) {
	r := client.R().SetContext(ctx)

	// process request parameters
	reqData, err := requeststruct.ResolveRequestParams(req)
	if err != nil {
		return nil, err
	}
	r.SetHeader("Content-Type", "application/json")
	r.SetHeader("Accept", "application/json")
	r.SetHeaders(reqData.HeaderParams)
	r.SetPathParams(reqData.PathParams)
	r.SetQueryParamsFromValues(reqData.QueryParams)
	if reqData.BodyParam != nil {
		r.SetBody(reqData.BodyParam)
	}
	result := new(models.ServiceMgmtServiceRegistryUnpublishPutResponse)
	r.SetResult(result)

	// send the request
	resp, err := r.Put("/serviceRegistry/unpublish")
	if err != nil {
		return nil, err
	}

	return &UnpublishFromServiceRegistryResponse{
		StatusCode:  resp.StatusCode(),
		RawResponse: resp.RawResponse,
		Result:      result,
	}, nil
}
