// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package operations

import (
	"context"
	"net/http"

	"github.com/go-resty/resty/v2"
	"github.com/primelib/primecodegen-lib-go/requeststruct"
	"github.com/primelib/webmethods-api-gateway-client/sdk/go/pkgs/models"
)

type UpdatePolicyActionRequest struct {
	PolicyActionId *string                               `pathParam:"style=simple,explode=false,name=policyActionId"` // This path parameter is used to specify the policy action id which needs to be updated.
	Payload        *models.PolicyMgmtPolicyActionWrapper `bodyParam:""`                                               // Contains the policy action details which needs to be updated.
}

type UpdatePolicyActionResponse struct {
	// Success response
	Result *models.PolicyMgmtPolicyActionWrapper
	// Error response
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

// UpdatePolicyAction This put request is used to update policy action based on the policy action id which is specified in path
//
//meta:operation PUT /policyActions/{policyActionId}
func UpdatePolicyAction(client *resty.Client, ctx context.Context, req UpdatePolicyActionRequest) (*UpdatePolicyActionResponse, error) {
	r := client.R().SetContext(ctx)

	// process request parameters
	reqData, err := requeststruct.ResolveRequestParams(req)
	if err != nil {
		return nil, err
	}
	r.SetHeader("Content-Type", "application/json")
	r.SetHeader("Accept", "application/json")
	r.SetHeaders(reqData.HeaderParams)
	r.SetPathParams(reqData.PathParams)
	r.SetQueryParamsFromValues(reqData.QueryParams)
	if reqData.BodyParam != nil {
		r.SetBody(reqData.BodyParam)
	}
	result := new(models.PolicyMgmtPolicyActionWrapper)
	r.SetResult(result)

	// send the request
	resp, err := r.Put("/policyActions/{policyActionId}")
	if err != nil {
		return nil, err
	}

	return &UpdatePolicyActionResponse{
		StatusCode:  resp.StatusCode(),
		RawResponse: resp.RawResponse,
		Result:      result,
	}, nil
}
