// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package operations

import (
	"context"
	"net/http"

	"github.com/go-resty/resty/v2"
	"github.com/primelib/primecodegen-lib-go/requeststruct"
	"github.com/primelib/webmethods-api-gateway-client/sdk/go/pkgs/models"
)

type UpdateAliasRequest struct {
	AliasId *string            `pathParam:"style=simple,explode=false,name=aliasId"` // The path parameter specifies the id of an alias whose detail is to be updated in API Gateway.
	Payload *models.AliasAlias `bodyParam:""`                                        // This parameter describes the request payload of an alias that is to be updated in API Gateway.
}

type UpdateAliasResponse struct {
	// Success response
	Result *models.AliasAlias
	// Error response
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

// UpdateAlias The method updates the details of a specified alias in API Gateway. The API request body must contain the payload of the alias that needs to be updated.
//
//meta:operation PUT /alias/{aliasId}
func UpdateAlias(client *resty.Client, ctx context.Context, req UpdateAliasRequest) (*UpdateAliasResponse, error) {
	r := client.R().SetContext(ctx)

	// process request parameters
	reqData, err := requeststruct.ResolveRequestParams(req)
	if err != nil {
		return nil, err
	}
	r.SetHeader("Content-Type", "application/json")
	r.SetHeader("Accept", "application/json")
	r.SetHeaders(reqData.HeaderParams)
	r.SetPathParams(reqData.PathParams)
	r.SetQueryParamsFromValues(reqData.QueryParams)
	if reqData.BodyParam != nil {
		r.SetBody(reqData.BodyParam)
	}
	result := new(models.AliasAlias)
	r.SetResult(result)

	// send the request
	resp, err := r.Put("/alias/{aliasId}")
	if err != nil {
		return nil, err
	}

	return &UpdateAliasResponse{
		StatusCode:  resp.StatusCode(),
		RawResponse: resp.RawResponse,
		Result:      result,
	}, nil
}
