// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package operations

import (
	"context"
	"net/http"

	"github.com/go-resty/resty/v2"
	"github.com/primelib/primecodegen-lib-go/requeststruct"
	"github.com/primelib/webmethods-api-gateway-client/sdk/go/pkgs/models"
)

type UpdateKeystoreAliasesRequest struct {
	KeyStoreName *string                        `pathParam:"style=simple,explode=false,name=keyStoreName"` // The name of the keystore. It cannot contain spaces or special characters. The name of the key store must be unique across all the keystores created in API Gateway.
	Payload      *models.UpdateKeystoreAliasesB `bodyParam:""`
}

type UpdateKeystoreAliasesResponse struct {
	// Success response
	Result *models.AdminKeyStore
	// Error response
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

// UpdateKeystoreAliases Updates an already existing keystore in API Gateway.
//
//meta:operation POST /is/keystore/{keyStoreName}
func UpdateKeystoreAliases(client *resty.Client, ctx context.Context, req UpdateKeystoreAliasesRequest) (*UpdateKeystoreAliasesResponse, error) {
	r := client.R().SetContext(ctx)

	// process request parameters
	reqData, err := requeststruct.ResolveRequestParams(req)
	if err != nil {
		return nil, err
	}
	r.SetHeader("Content-Type", "multipart/form-data")
	r.SetHeader("Accept", "application/json")
	r.SetHeaders(reqData.HeaderParams)
	r.SetPathParams(reqData.PathParams)
	r.SetQueryParamsFromValues(reqData.QueryParams)
	if reqData.BodyParam != nil {
		r.SetBody(reqData.BodyParam)
	}
	result := new(models.AdminKeyStore)
	r.SetResult(result)

	// send the request
	resp, err := r.Post("/is/keystore/{keyStoreName}")
	if err != nil {
		return nil, err
	}

	return &UpdateKeystoreAliasesResponse{
		StatusCode:  resp.StatusCode(),
		RawResponse: resp.RawResponse,
		Result:      result,
	}, nil
}
