// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package operations

import (
	"context"
	"net/http"

	"github.com/go-resty/resty/v2"
	"github.com/primelib/primecodegen-lib-go/requeststruct"
	"github.com/primelib/webmethods-api-gateway-client/sdk/go/pkgs/models"
)

type UpdateClusterRequest struct {
	Payload *models.AdminClusterInfo `bodyParam:""` // The request payload for cluster settings in API Gateway.
}

type UpdateClusterResponse struct {
	// Success response
	Result *models.AdminClusterInfo
	// Error response
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

// UpdateCluster Updates the cluster settings in API Gateway.
//
//meta:operation PUT /is/cluster
func UpdateCluster(client *resty.Client, ctx context.Context, req UpdateClusterRequest) (*UpdateClusterResponse, error) {
	r := client.R().SetContext(ctx)

	// process request parameters
	reqData, err := requeststruct.ResolveRequestParams(req)
	if err != nil {
		return nil, err
	}
	r.SetHeader("Content-Type", "application/json")
	r.SetHeader("Accept", "application/json")
	r.SetHeaders(reqData.HeaderParams)
	r.SetPathParams(reqData.PathParams)
	r.SetQueryParamsFromValues(reqData.QueryParams)
	if reqData.BodyParam != nil {
		r.SetBody(reqData.BodyParam)
	}
	result := new(models.AdminClusterInfo)
	r.SetResult(result)

	// send the request
	resp, err := r.Put("/is/cluster")
	if err != nil {
		return nil, err
	}

	return &UpdateClusterResponse{
		StatusCode:  resp.StatusCode(),
		RawResponse: resp.RawResponse,
		Result:      result,
	}, nil
}
