// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package operations

import (
	"context"
	"net/http"

	"github.com/go-resty/resty/v2"
	"github.com/primelib/primecodegen-lib-go/requeststruct"
	"github.com/primelib/webmethods-api-gateway-client/sdk/go/pkgs/models"
)

type UpdateOutboundProxyRequest struct {
	Payload *models.AdminOutboundProxySettings `bodyParam:""` // The request payload of an outbound proxy server that is to be updated in API Gateway.
}

type UpdateOutboundProxyResponse struct {
	// Error response
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

// UpdateOutboundProxy
//
//meta:operation PUT /is/outboundproxy
func UpdateOutboundProxy(client *resty.Client, ctx context.Context, req UpdateOutboundProxyRequest) (*UpdateOutboundProxyResponse, error) {
	r := client.R().SetContext(ctx)

	// process request parameters
	reqData, err := requeststruct.ResolveRequestParams(req)
	if err != nil {
		return nil, err
	}
	r.SetHeader("Content-Type", "application/json")
	r.SetHeaders(reqData.HeaderParams)
	r.SetPathParams(reqData.PathParams)
	r.SetQueryParamsFromValues(reqData.QueryParams)
	if reqData.BodyParam != nil {
		r.SetBody(reqData.BodyParam)
	}

	// send the request
	resp, err := r.Put("/is/outboundproxy")
	if err != nil {
		return nil, err
	}

	return &UpdateOutboundProxyResponse{
		StatusCode:  resp.StatusCode(),
		RawResponse: resp.RawResponse,
	}, nil
}
