// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package operations

import (
	"context"
	"net/http"

	"github.com/go-resty/resty/v2"
	"github.com/primelib/primecodegen-lib-go/requeststruct"
	"github.com/primelib/webmethods-api-gateway-client/sdk/go/pkgs/models"
)

type UpdateListenerConfigurationRequest struct {
	Payload *models.DataMgmtListenerConfig `bodyParam:""` // Listener configuration payload
}

type UpdateListenerConfigurationResponse struct {
	// Success response
	Result *models.DataMgmtListenerConfig
	// Error response
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

// UpdateListenerConfiguration The method is used to configure the listener in the datacenter in API Gateway.
//
//meta:operation PUT /dataspace/listener
func UpdateListenerConfiguration(client *resty.Client, ctx context.Context, req UpdateListenerConfigurationRequest) (*UpdateListenerConfigurationResponse, error) {
	r := client.R().SetContext(ctx)

	// process request parameters
	reqData, err := requeststruct.ResolveRequestParams(req)
	if err != nil {
		return nil, err
	}
	r.SetHeader("Content-Type", "application/json")
	r.SetHeader("Accept", "application/json")
	r.SetHeaders(reqData.HeaderParams)
	r.SetPathParams(reqData.PathParams)
	r.SetQueryParamsFromValues(reqData.QueryParams)
	if reqData.BodyParam != nil {
		r.SetBody(reqData.BodyParam)
	}
	result := new(models.DataMgmtListenerConfig)
	r.SetResult(result)

	// send the request
	resp, err := r.Put("/dataspace/listener")
	if err != nil {
		return nil, err
	}

	return &UpdateListenerConfigurationResponse{
		StatusCode:  resp.StatusCode(),
		RawResponse: resp.RawResponse,
		Result:      result,
	}, nil
}
