// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

// AdminMasterPasswordExpiryInterval The expiration interval is a recommended time between master password changes.The default expiration interval for a master password is 90 days.After the expiration date,API Gateway will continue to operate using the existing password indefinitely.

type AdminMasterPasswordExpiryInterval struct {
	ExpireInterval *string `json:"expireInterval" form:"name=expireInterval"` // This interval(in days) specifies the time after which the master password would expire
}
