// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

// AdminErrorProcessing Defines the error message configuration. The configured error message will be sent to the invoking client in case API Gateway encounters an exception.

type AdminErrorProcessing struct {
	DefaultErrorMessage     *string `json:"defaultErrorMessage" form:"name=defaultErrorMessage"`
	FallbackErrorMessage    *string `json:"fallbackErrorMessage" form:"name=fallbackErrorMessage"`
	SendNativeProvIDErFault *string `json:"sendNativeProviderFault" form:"name=sendNativeProviderFault"`
}
