// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

// AdminCscommunicationDestination This defines the configurations required for Centrasite Communication section of CentraSite destination.

type AdminCscommunicationDestination struct {
	GatewayAssetId *string `json:"gatewayAssetId" form:"name=gatewayAssetId"` // Specifies the registered API Gateway ID.
	Hostname       *string `json:"hostname" form:"name=hostname"`             // Specifies the host name or IP address of the machine on which CentraSite Application Server Tier (CAST) is running.
	Password       *string `json:"password" form:"name=password"`             // Specifies the password for authenticating CentraSite when API Gateway communicates with CentraSite.
	Protocol       *string `json:"protocol" form:"name=protocol"`             // Specifies the communication protocol used to establish communication between API Gateway and CentraSite.
	Targetname     *string `json:"targetname" form:"name=targetname"`         // Specifies the name of the API Gateway asset as defined in CentraSite.
	UddiPort       *string `json:"uddiPort" form:"name=uddiPort"`             // Specifies the port on which CAST is listening. The default port number for CAST is 53307.
	Username       *string `json:"username" form:"name=username"`             // Specifies the CentraSite user ID for authenticating CentraSite when API Gateway communicates with CentraSite. This implies the user ID of a user who has the CentraSite Administrator role or the API Gateway Administrator role in CentraSite.
}
