// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type AdminProductInformation struct {
	ExpirationDate    *string `json:"Expiration Date" form:"name=Expiration Date"`
	HigherLevPosNr    *string `json:"HigherLevPosNr" form:"name=HigherLevPosNr"`
	HigherLevProdCode *string `json:"HigherLevProdCode" form:"name=HigherLevProdCode"`
	HigherLevProdName *string `json:"HigherLevProdName" form:"name=HigherLevProdName"`
	OperatingSystem   *string `json:"Operating System" form:"name=Operating System"`
	ProductCode       *string `json:"Product Code" form:"name=Product Code"`
	ProductId         *string `json:"Product ID" form:"name=Product ID"`
	ProductName       *string `json:"Product Name" form:"name=Product Name"`
	ProductVersion    *string `json:"Product Version" form:"name=Product Version"`
	RenewalDate       *string `json:"RenewalDate" form:"name=RenewalDate"`
	Usage             *string `json:"Usage" form:"name=Usage"`
}
