// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

// AdminWebhook This model contains details about a webhook in API Gateway

type AdminWebhook struct {
	Active *bool               `json:"active" form:"name=active"`      // Specifies whether this webhook is active or not. Default value is false.
	Config *AdminWebhookConfig `json:"config" form:"name=config,json"` // This model contains webhook configuration details like url, headers, etc in API Gateway
	Events []*string           `json:"events" form:"name=events,json"` // The list of interested events this webhook is subscribed for
	Id     *string             `json:"id" form:"name=id"`              // A unique ID for the webhook
}
