// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type AdminDenyByIpforFailedAuthConfig struct {
	BlockIntervalInSeconds            *string   `json:"blockIntervalInSeconds" form:"name=blockIntervalInSeconds"`                       // Specifies the block time interval(in seconds) for an IP address from accessing APIGateway
	DeniedIplist                      []*string `json:"deniedIPList" form:"name=deniedIPList,json"`                                      // Specifies list of IP addresses that are denied from accessing APIGateway
	IsEnabled                         *string   `json:"isEnabled" form:"name=isEnabled"`                                                 // Specifies whether to enable authentication based restrictions by blocking/denying IP addresses which failed authentication.
	MaximumFailedAuthRequests         *string   `json:"maximumFailedAuthRequests" form:"name=maximumFailedAuthRequests"`                 // Specifies maximum failed requests for a particular IP address.
	MaximumFailedAuthRequestsDuration *string   `json:"maximumFailedAuthRequestsDuration" form:"name=maximumFailedAuthRequestsDuration"` // Specifies the time interval, in seconds, in which maximum authentication failure can be permitted.
	WhenLimitExceeds                  *string   `json:"whenLimitExceeds" form:"name=whenLimitExceeds"`                                   // Specifies action to be performed when maximum failed request is breached. The value can be BLOCK or DENY
}
