// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

// AdminElasticsearchConfig This model contains details about Elasticsearch endpoint

type AdminElasticsearchConfig struct {
	KeystoreAlias      *string `json:"keystoreAlias" form:"name=keystoreAlias"`
	KeystoreFilePath   *string `json:"keystoreFilePath" form:"name=keystoreFilePath"`
	KeystorePassword   *string `json:"keystorePassword" form:"name=keystorePassword"`
	Password           *string `json:"password" form:"name=password"` // The password required to authenticate if authentication is enabled for the source Elasticsearch instance.
	TruststoreFilePath *string `json:"truststoreFilePath" form:"name=truststoreFilePath"`
	TruststorePassword *string `json:"truststorePassword" form:"name=truststorePassword"`
	Url                *string `json:"url" form:"name=url"`           // The source Elasticsearch instance URL
	Username           *string `json:"username" form:"name=username"` // The user name required to authenticate against if authentication is enabled for the source Elasticsearch instance.
}
