// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type AdminProxyBypass struct {
	EntityId             *string   `json:"entityId" form:"name=entityId"`                              // proxyBypass constance Fixed unique identifier value is proxyBypass
	ProxyBypassAddresses []*string `json:"proxyBypassAddresses" form:"name=proxyBypassAddresses,json"` // The host name or IP address of the server. In the Addresses field, type the fully qualified host and domain name of each server to which you want the Integration Server to issue requests directly. Type the host name and the domain name exactly as they appear in the URLs the server uses. To enter multiple names, separate each with commas. You can use the asterisk (*) to identify several servers with similar names. The asterisk matches any number of characters. For example, if you want to bypass requests made to localhost, www.yahoo.com, home.microsoft.com, and all hosts whose names begin with NYC, you would type: localhost,www.yahoo.com,home.microsoft.com, NYC*.*
}
