// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type AdminMasterPasswordUpdateResponse struct {
	Message *string `json:"message" form:"name=message"` // The response message from the server when the master password is updated
}
