// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type AdminRule struct {
	Active              *bool                  `json:"active" form:"name=active"`                            // This rule is active
	AttributeContexts   []*string              `json:"attributeContexts" form:"name=attributeContexts,json"` // Context(s) of the attribute used in rule expression
	Description         *string                `json:"description" form:"name=description"`                  // Rule Description
	Id                  *string                `json:"id" form:"name=id"`                                    // A unique ID for the rule
	Name                *string                `json:"name" form:"name=name"`                                // Rule name
	Owner               *string                `json:"owner" form:"name=owner"`                              // Owner of this rule asset
	RuleExpressions     []*AdminRuleExpression `json:"ruleExpressions" form:"name=ruleExpressions,json"`     // Rule condition is defined using ruleExpressions
	RuleLogicalOperator *string                `json:"ruleLogicalOperator" form:"name=ruleLogicalOperator"`  // Logical operator (AND / OR) that should be used to evaluate Rule expression
	RuleType            *string                `json:"ruleType" form:"name=ruleType"`                        // Type of the rule
}
