// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

// AdminKeystoreTruststore This defines the keystore and truststore requred for the API Gateway.

type AdminKeystoreTruststore struct {
	ConfigId               *string `json:"configId" form:"name=configId"`
	KeystoreName           *string `json:"keystoreName" form:"name=keystoreName"`
	OutboundKeyAlias       *string `json:"outboundKeyAlias" form:"name=outboundKeyAlias"`
	OutboundKeystoreName   *string `json:"outboundKeystoreName" form:"name=outboundKeystoreName"`
	OutboundTruststoreName *string `json:"outboundTruststoreName" form:"name=outboundTruststoreName"`
	SigningAlias           *string `json:"signingAlias" form:"name=signingAlias"`
	TruststoreName         *string `json:"truststoreName" form:"name=truststoreName"`
}
