// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

// AdminCssnmpdestination This defines the configurations required for CentraSite SNMP section of CentraSite destination.

type AdminCssnmpdestination struct {
	AuthorizationPassword *string `json:"authorizationPassword" form:"name=authorizationPassword"` // Specifies the password to be used for authorization protocol.
	AuthorizationProtocol *string `json:"authorizationProtocol" form:"name=authorizationProtocol"` // Specifies the authorization protocol that is used by the SNMP Listener for decoding the incoming trap.
	Hostname              *string `json:"hostname" form:"name=hostname"`                           // Specifies the CentraSite host name or IP address to which the SNMP listener binds.
	Port                  *string `json:"port" form:"name=port"`                                   // Specifies the port to which the SNMP listener binds. The default port number for CentraSite's SNMP server is 8181.
	PrivacyPassword       *string `json:"privacyPassword" form:"name=privacyPassword"`             // Specifies the password to be used for privacy protocol.
	PrivacyProtocol       *string `json:"privacyProtocol" form:"name=privacyProtocol"`             // Specifies the privacy protocol that is used by the SNMP Listener for decoding the incoming trap.
	SendTrapsToCentrasite *string `json:"sendTRAPsToCentrasite" form:"name=sendTRAPsToCentrasite"` // Specifies whether the events has to be sent from API Gateway to CentraSite.
	Transport             *string `json:"transport" form:"name=transport"`                         // Specifies the wire transport protocol that is used by the SNMP Listener.
	Username              *string `json:"username" form:"name=username"`                           // Specifies the SecurityName that is used by the SNMP Listener.
}
