// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

// AdminLoadBalancer This defines the Load Balancer URLs configuration in the API Gateway.

type AdminLoadBalancer struct {
	HttpUrls      []*string `json:"httpUrls" form:"name=httpUrls,json"`           // HTTP URLs to be exposed for API invocation.
	HttpsUrls     []*string `json:"httpsUrls" form:"name=httpsUrls,json"`         // HTTPS URLs to be exposed for API invocation.
	WebAppUrl     *string   `json:"webAppUrl" form:"name=webAppUrl"`              // API Gateway UI access url
	WebsocketUrls []*string `json:"websocketUrls" form:"name=websocketUrls,json"` // WebSocket URL to be exposed for Websocket APIs invocation.
}
