// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

// AdminWhiteListedIps This defines the whitelisting of private IPs configured in the API Gateway.

type AdminWhiteListedIps struct {
	PrivateIps   []*string `json:"privateIPs" form:"name=privateIPs,json"`     // List of private whitelisted IPs to be considered while API is created / updated by importing a url and import an archive
	PrivateV6Ips []*string `json:"privateV6IPs" form:"name=privateV6IPs,json"` // List of whitelisted IPV6 private IPs to be considered while API is created / updated by importing a url and import an archive
}
