// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

// AdminMasterPasswordProperties Describes the master password configuration properties in API Gateway

type AdminMasterPasswordProperties struct {
	DaysTilExpire  *string `json:"daysTilExpire" form:"name=daysTilExpire"`   // The remaining number of days for the master password expiration
	ExpireDate     *string `json:"expireDate" form:"name=expireDate"`         // The expiry date of the master password.The format for this field would be YYYY-MM-DD HH:mm:ssZ
	ExpireInterval *string `json:"expireInterval" form:"name=expireInterval"` // The interval(in days) after which the master password would expire
	ExpireMessage  *string `json:"expireMessage" form:"name=expireMessage"`   // The message which will be returned once the master password is expired
	LastChangeDate *string `json:"lastChangeDate" form:"name=lastChangeDate"` // The latest date when the master password was updated.The format for this field would be YYYY-MM-DD HH:mm:ssZ
	StatusMessage  *string `json:"statusMessage" form:"name=statusMessage"`   // The current status of the master password
}
