// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type AliasLocalIntrospectionConfig struct {
	CertificateAlias  *string `json:"certificateAlias" form:"name=certificateAlias"`   // Select the certificate from the truststore that is used to validate the token.
	Description       *int32  `json:"description" form:"name=description"`             // Specifies the clock skew in seconds to validate JWT
	Issuer            *string `json:"issuer" form:"name=issuer"`                       // Third party issuer name
	Jwksuri           *string `json:"jwksuri" form:"name=jwksuri"`                     // JSON Web Key URI
	TrustStoreAlias   *string `json:"trustStoreAlias" form:"name=trustStoreAlias"`     // The truststore to be used by API Gateway when validating the token issued by the authorization server. Truststore is a repository that holds all the trusted public certificates
	UseLocalClockSkew *bool   `json:"useLocalClockSkew" form:"name=useLocalClockSkew"` // Specifies whether to use the local clock skew for validating JWT.
}
