// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type AliasScope struct {
	Description *string `json:"description" form:"name=description"` // Description of the oauth2 scope
	Name        *string `json:"name" form:"name=name"`               // Name of the oauth2 scope
}
