// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type AliasRemoteIntrospectionConfig struct {
	ClientId              *string             `json:"clientId" form:"name=clientId"` // ClientId of a client in the authorization server
	ClientSecret          *AliasGatewaySecret `json:"clientSecret" form:"name=clientSecret,json"`
	IntrospectionEndpoint *string             `json:"introspectionEndpoint" form:"name=introspectionEndpoint"` // Endpoint of the authorization server to do the introspection
	User                  *string             `json:"user" form:"name=user"`                                   // A user in the API Gateway under whom the introspection endpoint is invoked
}
