// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type AliasOauth2Endpoints struct {
	Endpoints     *Endpoints `json:"endpoints" form:"name=endpoints,json"`
	KeyAlias      *string    `json:"keyAlias" form:"name=keyAlias"`
	KeyStoreAlias *string    `json:"keyStoreAlias" form:"name=keyStoreAlias"`
}
