// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type AliasTokenGeneratorConfig struct {
	AccessTokenExpInterval *int32  `json:"accessTokenExpInterval" form:"name=accessTokenExpInterval"` // Expiry interval in seconds for the generated access token
	Algorithm              *string `json:"algorithm" form:"name=algorithm"`                           // Type of algorithm that needs to be used for signing the JWT
	Audience               *string `json:"audience" form:"name=audience"`                             // Default audience value that needs to be added in the generated JWT
	AuthCodeExpInterval    *int32  `json:"authCodeExpInterval" form:"name=authCodeExpInterval"`       // Expiry interval in seconds for the generated authorization code in Authorization code grant type
	EnforcePkce            *bool   `json:"enforcePKCE" form:"name=enforcePKCE"`                       // Global option to apply PKCE security, for the public clients using authorization code grant type. Applicable only for local auth server
	Expiry                 *int64  `json:"expiry" form:"name=expiry"`                                 // Expiry interval of the JWT in minutes
}
