// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type AliasSignAndEncryptConfig struct {
	CertificateAlias *string `json:"certificateAlias" form:"name=certificateAlias"` // Select the certificate from the truststore that is used to validate the request that is sent to the native API.
	KeyAlias         *string `json:"keyAlias" form:"name=keyAlias"`                 // The key alias is the private key that is used sign the request sent to the native API
	KeyStoreAlias    *string `json:"keyStoreAlias" form:"name=keyStoreAlias"`       // Specify the keystore that needs to be used by API Gateway while sending the request to the native API. A keystore is a repository of private key and its corresponding public certificate
	TruststoreAlias  *string `json:"truststoreAlias" form:"name=truststoreAlias"`   // The truststore to be used by API Gateway when sending the request to the native API. Truststore is a repository that holds all the trusted public certificates
}
