// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type ApplicationJwthsauthStrategy struct {
	Audience        *string                   `json:"audience" form:"name=audience"`
	AuthServerAlias *string                   `json:"authServerAlias" form:"name=authServerAlias"` // The name of the authorization server alias
	Description     *string                   `json:"description" form:"name=description"`
	Id              *string                   `json:"id" form:"name=id"`     // A unique ID for the strategy
	Name            *string                   `json:"name" form:"name=name"` // The name of the strategy
	PrimaryNode     *ApplicationNode          `json:"primaryNode" form:"name=primaryNode,json"`
	Secret          *ApplicationGatewaySecret `json:"secret" form:"name=secret,json"`
	Type            *string                   `json:"type" form:"name=type"` // Input file type
}
