// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

// DirectiveDefinitions GraphQL directive definitions
type DirectiveDefinitions map[*string]*ServiceMgmtGqlDirectiveDefinition
