// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

// From from value is used to set the minimum value in the request criteria and it can be integer, date or datetime
type From *interface{}
