// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type HealthCheckAllResult struct {
	Admin    *HealthCheckAdminResult    `json:"admin" form:"name=admin,json"`
	Engine   *HealthCheckEngineResult   `json:"engine" form:"name=engine,json"`
	External *HealthCheckExternalResult `json:"external" form:"name=external,json"`
}
