// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type MonetizationApplicationIDEntifier struct {
	Id    *string   `json:"id" form:"name=id"`            // unique identifier of the application identifier
	Key   *string   `json:"key" form:"name=key"`          // identifier type
	Name  *string   `json:"name" form:"name=name"`        // name of the identifier
	Value []*string `json:"value" form:"name=value,json"` // list of identifier values
}
