// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type MonetizationGqlOperationTypeDefinition struct {
	Comments []*MonetizationGqlComment `json:"comments" form:"name=comments,json"` // List of comments
	Enabled  *bool                     `json:"enabled" form:"name=enabled"`        // Flag to specify if this field is enabled or not
	Name     *string                   `json:"name" form:"name=name"`              // Name of the operation type definition
	TypeName *MonetizationGqlTypeName  `json:"typeName" form:"name=typeName,json"`
}
