// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type MonetizationGqlObjectField struct {
	Comments []*MonetizationGqlComment `json:"comments" form:"name=comments,json"` // List of comments
	Name     *string                   `json:"name" form:"name=name"`              // Name of the object field
	Value    *MonetizationGqlValue     `json:"value" form:"name=value,json"`
}
