// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type MonetizationModel struct {
	Description      *string                   `json:"description" form:"name=description"`
	Example          *interface{}              `json:"example" form:"name=example,json"` // A free-form property to include an example of an instance for this schema. To represent examples that cannot be naturally represented in JSON or YAML, a string value can be used to contain the example with escaping where necessary
	ExternalDocs     *MonetizationExternalDocs `json:"externalDocs" form:"name=externalDocs,json"`
	Properties       *Properties               `json:"properties" form:"name=properties,json"` // The properties (key-value pairs) on an object are defined using the properties keyword. The value of properties is an object, where each key is the name of a property and each value is of type schema used to validate that property
	Reference        *string                   `json:"reference" form:"name=reference"`
	Title            *string                   `json:"title" form:"name=title"`
	Type             *string                   `json:"type" form:"name=type"`
	VendorExtensions *VendorExtensions         `json:"vendorExtensions" form:"name=vendorExtensions,json"`
}
