// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type MonetizationTag struct {
	Description      *string                   `json:"description" form:"name=description"` // A short description for the tag
	ExternalDocs     *MonetizationExternalDocs `json:"externalDocs" form:"name=externalDocs,json"`
	Name             *string                   `json:"name" form:"name=name"` // The name of the tag
	VendorExtensions *VendorExtensions         `json:"vendorExtensions" form:"name=vendorExtensions,json"`
}
