// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type MonetizationActionImport struct {
	Action  *string `json:"action" form:"name=action"`
	Enabled *bool   `json:"enabled" form:"name=enabled"`
}
