// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type MonetizationOauthFlows struct {
	AuthorizationCode *MonetizationOauth2Definition `json:"authorizationCode" form:"name=authorizationCode,json"`
	ClientCredentials *MonetizationOauth2Definition `json:"clientCredentials" form:"name=clientCredentials,json"`
	Implicit          *MonetizationOauth2Definition `json:"implicit" form:"name=implicit,json"`
	Password          *MonetizationOauth2Definition `json:"password" form:"name=password,json"`
	VendorExtensions  *VendorExtensions             `json:"vendorExtensions" form:"name=vendorExtensions,json"`
}
