// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type MonetizationSoapoperation struct {
	Bindings                                 []*MonetizationSoapbinding                         `json:"bindings" form:"name=bindings,json"`
	Defined                                  *bool                                              `json:"defined" form:"name=defined"`
	Enabled                                  *bool                                              `json:"enabled" form:"name=enabled"`
	Headers                                  []*string                                          `json:"headers" form:"name=headers,json"`
	IsRestinvokeEnabled                      *bool                                              `json:"isRESTInvokeEnabled" form:"name=isRESTInvokeEnabled"`
	MockedConditionsBasedCustomResponsesList []*MonetizationMockedConditionsBasedCustomResponse `json:"mockedConditionsBasedCustomResponsesList" form:"name=mockedConditionsBasedCustomResponsesList,json"`
	MockedResponses                          *MockedResponses                                   `json:"mockedResponses" form:"name=mockedResponses,json"`
	Name                                     *string                                            `json:"name" form:"name=name"`
	Namespace                                *string                                            `json:"namespace" form:"name=namespace"`
	RestEnabledPath                          *MonetizationRestEnabledPath                       `json:"restEnabledPath" form:"name=restEnabledPath,json"`
	Scopes                                   []*string                                          `json:"scopes" form:"name=scopes,json"`
	SoapAction                               *string                                            `json:"soapAction" form:"name=soapAction"`
	Tags                                     []*string                                          `json:"tags" form:"name=tags,json"`
}
