// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type MonetizationGqlDirectiveDefinition struct {
	Comments              []*MonetizationGqlComment              `json:"comments" form:"name=comments,json"` // List of comments
	Description           *MonetizationGqlDescription            `json:"description" form:"name=description,json"`
	DirectiveLocations    []*MonetizationGqlDirectiveLocation    `json:"directiveLocations" form:"name=directiveLocations,json"`       // List of directive locations
	InputValueDefinitions []*MonetizationGqlInputValueDefinition `json:"inputValueDefinitions" form:"name=inputValueDefinitions,json"` // List of input value type definitions
	Name                  *string                                `json:"name" form:"name=name"`                                        // Name of the directive
}
