// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type MonetizationPackageGetResponseContainer struct {
	PackageResponse *MonetizationPackageResponse `json:"packageResponse" form:"name=packageResponse,json"`
}
