// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type MonetizationMethodParameters struct {
	Enabled    *bool       `json:"enabled" form:"name=enabled"`
	Parameters *Parameters `json:"parameters" form:"name=parameters,json"`
	ReturnType *string     `json:"returnType" form:"name=returnType"`
}
