// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type PolicyMgmtPolicyActionWrapper struct {
	PolicyAction *PolicyMgmtPolicyAction `json:"policyAction" form:"name=policyAction,json"` // This model contains details about a policy action in API Gateway
}
