// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

// Properties The properties (key-value pairs) on an object are defined using the properties keyword. The value of properties is an object, where each key is the name of a property and each value is of type schema used to validate that property
type Properties map[*string]*ServiceMgmtSchema
