// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

// SearchIaggregation This defines the aggregation structure to search across API Gateway

type SearchIaggregation struct {
	Fields *string `json:"fields" form:"name=fields"` // Input aggregation fields
	Name   *string `json:"name" form:"name=name"`     // Name of the aggregation in the search aggregation response
	Type   *string `json:"type" form:"name=type"`     // Input file type
}
