// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

// ServiceMgmtGatewayScope Maps the authorization server scope with APIs or API scopes

type ServiceMgmtGatewayScope struct {
	APIScopes          []*string                     `json:"apiScopes" form:"name=apiScopes,json"`                   // List of API IDs (or API Scope IDs) mapped the auth server scope
	Audience           *string                       `json:"audience" form:"name=audience"`                          // This field is optional. This value will be used in scope level audience matching
	Id                 *string                       `json:"id" form:"name=id"`                                      // A unique ID for the OAuth scope mapping
	RequiredAuthScopes []*ServiceMgmtAuthServerScope `json:"requiredAuthScopes" form:"name=requiredAuthScopes,json"` // List of oauth scope entries from the authorization server definition
	ScopeDescription   *string                       `json:"scopeDescription" form:"name=scopeDescription"`          // Description for the OAuth scope mapping
	ScopeName          *string                       `json:"scopeName" form:"name=scopeName"`                        // Name of the OAuth scope mapping
}
