// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type ServiceMgmtMultipart struct {
	ContentType *string          `json:"contentType" form:"name=contentType"`
	Count       *int32           `json:"count" form:"name=count"`
	Parent      *ServiceMgmtPart `json:"parent" form:"name=parent,json"`
}
