// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type ServiceMgmtLicence struct {
	Name             *string           `json:"name" form:"name=name"` // The license name used for the API
	Url              *string           `json:"url" form:"name=url"`   // A URL to the license used for the API
	VendorExtensions *VendorExtensions `json:"vendorExtensions" form:"name=vendorExtensions,json"`
}
