// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type ServiceMgmtEndpoint struct {
	Alias                     *bool   `json:"alias" form:"name=alias"`
	ConnectionTimeoutDuration *int32  `json:"connectionTimeoutDuration" form:"name=connectionTimeoutDuration"`
	OptimizationTechnique     *string `json:"optimizationTechnique" form:"name=optimizationTechnique"`
	PassSecurityHeaders       *bool   `json:"passSecurityHeaders" form:"name=passSecurityHeaders"`
	Uri                       *string `json:"uri" form:"name=uri"`
}
