// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type ServiceMgmtFunctionImport struct {
	Enabled  *bool   `json:"enabled" form:"name=enabled"`
	Function *string `json:"function" form:"name=function"`
}
