// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type ServiceMgmtEndpointInfo struct {
	Endpoint      *string `json:"endpoint" form:"name=endpoint"`
	GatewayPoolId *string `json:"gatewayPoolId" form:"name=gatewayPoolId"`
}
