// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type ServiceMgmtGqlInputValueDefinition struct {
	Comments         []*ServiceMgmtGqlComment   `json:"comments" form:"name=comments,json"` // List of comments
	DefaultValue     *ServiceMgmtGqlValue       `json:"defaultValue" form:"name=defaultValue,json"`
	Description      *ServiceMgmtGqlDescription `json:"description" form:"name=description,json"`
	Directives       []*ServiceMgmtGqlDirective `json:"directives" form:"name=directives,json"` // List of directives
	DirectivesByName *DirectivesByName          `json:"directivesByName" form:"name=directivesByName,json"`
	Name             *string                    `json:"name" form:"name=name"` // Name of the input value definition
	Type             *ServiceMgmtGqlType        `json:"type" form:"name=type,json"`
}
