// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type ServiceMgmtIntegrationServerPublishResponse struct {
	Description           *string `json:"description" form:"name=description"`                 // Represents the status of the publish operation of the API to the service registry eg: Publish successful, Publish failed, etc
	FailureReason         *string `json:"failureReason" form:"name=failureReason"`             // Provides the reason for the failure when the publish operation is not successful
	IntegrationServerId   *string `json:"integrationServerId" form:"name=integrationServerId"` // Id i.e, UDDI key of the service registry
	IntegrationServerName *string `json:"integrationServerName" form:"name=integrationServerName"`
	Status                *string `json:"status" form:"name=status"`   // Publish Status of the API for this service registry. Possible values are NEW, PUBLISHED and SUSPENDED. NEW represents the API is not published to the service registry. PUBLISHED represents the API is published to the service registry. SUSPENDED represents the API is published to service registry, but is not currently active (during deactivation of API or shutdown of API Gateway).
	Success               *bool   `json:"success" form:"name=success"` // Represents whether the publish of API to the service registry is success. Possible values: true/false
}
