// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type ServiceMgmtExternalDocs struct {
	Description      *string           `json:"description" form:"name=description"` // A short description of the target documentation
	Url              *string           `json:"url" form:"name=url"`                 // The URL for the target documentation
	VendorExtensions *VendorExtensions `json:"vendorExtensions" form:"name=vendorExtensions,json"`
}
