// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type ServiceMgmtOperation struct {
	Callbacks                                *Callbacks                                        `json:"callbacks" form:"name=callbacks,json"` // An optional, string description, intended to apply to all operations in this path
	Deprecated                               *bool                                             `json:"deprecated" form:"name=deprecated"`    // Declares this operation to be deprecated. Consumers SHOULD refrain from usage of the declared operation. Default value is false
	Description                              *string                                           `json:"description" form:"name=description"`  // A verbose explanation of the operation behavior
	Enabled                                  *bool                                             `json:"enabled" form:"name=enabled"`
	ExternalDocs                             *ServiceMgmtExternalDocs                          `json:"externalDocs" form:"name=externalDocs,json"`
	MockedConditionsBasedCustomResponsesList []*ServiceMgmtMockedConditionsBasedCustomResponse `json:"mockedConditionsBasedCustomResponsesList" form:"name=mockedConditionsBasedCustomResponsesList,json"` // The list of mocked conditions and it's applicable only for mocked APIs
	MockedResponses                          *MockedResponses                                  `json:"mockedResponses" form:"name=mockedResponses,json"`
	OperationId                              *string                                           `json:"operationId" form:"name=operationId"`    // Unique string used to identify the operation. The id MUST be unique among all operations described in the API. The operationId value is case-sensitive
	Parameters                               []*ServiceMgmtParameter                           `json:"parameters" form:"name=parameters,json"` // A list of parameters that are applicable for this operation. If a parameter is already defined at the Path Item, the new definition will override it but can never remove it
	RequestBody                              *ServiceMgmtRequestBody                           `json:"requestBody" form:"name=requestBody,json"`
	Responses                                *Responses                                        `json:"responses" form:"name=responses,json"`
	Scopes                                   []*string                                         `json:"scopes" form:"name=scopes,json"`
	Summary                                  *string                                           `json:"summary" form:"name=summary"` // A short summary of what the operation does
	Tags                                     []*string                                         `json:"tags" form:"name=tags,json"`  // A list of tags for API documentation control. Tags can be used for logical grouping of operations by resources or any other qualifier
	VendorExtensions                         *VendorExtensions                                 `json:"vendorExtensions" form:"name=vendorExtensions,json"`
}
