// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type ServiceMgmtServiceRegistryPublishResponse struct {
	Description         *string                 `json:"description" form:"name=description"`                 // Represents the status of the publish operation of the API to the service registry eg: Publish successful, Publish failed, etc
	FailureReason       *string                 `json:"failureReason" form:"name=failureReason"`             // Provides the reason for the failure when the publish operation is not successful
	GatewayEndpoints    []*ServiceMgmtEndpoints `json:"gatewayEndpoints" form:"name=gatewayEndpoints,json"`  // List of API endpoints of the API. Each element contains an endpoint and the information about the publish status of that endpoint for the current service registry.
	ServiceRegistryId   *string                 `json:"serviceRegistryId" form:"name=serviceRegistryId"`     // Id i.e, UDDI key of the service registry
	ServiceRegistryName *string                 `json:"serviceRegistryName" form:"name=serviceRegistryName"` // Name of the service registry
	Status              *string                 `json:"status" form:"name=status"`                           // Publish Status of the API for this service registry. Possible values are NEW, PUBLISHED and SUSPENDED. NEW represents the API is not published to the service registry. PUBLISHED represents the API is published to the service registry. SUSPENDED represents the API is published to service registry, but is not currently active (during deactivation of API or shutdown of API Gateway).
	Success             *bool                   `json:"success" form:"name=success"`                         // Represents whether the publish of API to the service registry is success. Possible values: true/false
}
