// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type ServiceMgmtPublishPayload struct {
	APIId                        *string                                    `json:"apiId" form:"name=apiId"` // API id for the API to be published. This field is required. The API will be published to the service registry with the value configured in 'Service registry display name' field of the API
	IntegrationServerPublishInfo []*ServiceMgmtIntegrationServerPublishInfo `json:"integrationServerPublishInfo" form:"name=integrationServerPublishInfo,json"`
	ServiceRegistryPublishInfo   []*ServiceMgmtServiceRegistryPublishInfo   `json:"serviceRegistryPublishInfo" form:"name=serviceRegistryPublishInfo,json"` // List of service registry publish information for the API. Each element of the list contains the publish information of the API for one service registry.
}
