// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

// ServiceMgmtInputForGatewayEndpoints To manage gateway endpoints of an API

type ServiceMgmtInputForGatewayEndpoints struct {
	Add    *ServiceMgmtInputForAddGatewayEndpoint    `json:"add" form:"name=add,json"`       // To add a new Gateway endpoint of this API
	Remove *ServiceMgmtInputForRemoveGatewayEndpoint `json:"remove" form:"name=remove,json"` // To remove an existing Gateway endpoint of this API
	Update *ServiceMgmtInputForUpdateGatewayEndpoint `json:"update" form:"name=update,json"` // To update an existing Gateway endpoint of this API
}
