// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type ServiceMgmtMockedCondition struct {
	ConditionName            *string `json:"conditionName" form:"name=conditionName"`
	MockedConditionParameter *string `json:"mockedConditionParameter" form:"name=mockedConditionParameter"`
	MockedLevel1Operator     *string `json:"mockedLevel1Operator" form:"name=mockedLevel1Operator"`
	MockedLevel2Operator     *string `json:"mockedLevel2Operator" form:"name=mockedLevel2Operator"`
	Value1                   *string `json:"value1" form:"name=value1"`
	Value2                   *string `json:"value2" form:"name=value2"`
}
