// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type ServiceMgmtOauthFlows struct {
	AuthorizationCode *ServiceMgmtOauth2Definition `json:"authorizationCode" form:"name=authorizationCode,json"`
	ClientCredentials *ServiceMgmtOauth2Definition `json:"clientCredentials" form:"name=clientCredentials,json"`
	Implicit          *ServiceMgmtOauth2Definition `json:"implicit" form:"name=implicit,json"`
	Password          *ServiceMgmtOauth2Definition `json:"password" form:"name=password,json"`
	VendorExtensions  *VendorExtensions            `json:"vendorExtensions" form:"name=vendorExtensions,json"`
}
