// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type ServiceMgmtScopeReferences struct {
	Scopes []*ServiceMgmtScopeResourceIndex `json:"scopes" form:"name=scopes,json"` // List of scopes
}
