// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type ServiceMgmtMockedConditionsBasedCustomResponse struct {
	MockedConditionList []*ServiceMgmtMockedCondition `json:"mockedConditionList" form:"name=mockedConditionList,json"`
	MockedResponse      *ServiceMgmtMockedResponse    `json:"mockedResponse" form:"name=mockedResponse,json"`
}
