// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type ServiceMgmtUnpublishResponse struct {
	APIId                             *string                                        `json:"apiId" form:"name=apiId"`                                                              // API id of the API published.
	APIName                           *string                                        `json:"apiName" form:"name=apiName"`                                                          // API name of the API published.
	APIVersion                        *string                                        `json:"apiVersion" form:"name=apiVersion"`                                                    // API version of the API published.
	ServiceRegistryUnpublishResponses []*ServiceMgmtServiceRegistryUnpublishResponse `json:"serviceRegistryUnpublishResponses" form:"name=serviceRegistryUnpublishResponses,json"` // Contains unpublish status of the API for each service registry in the request.
}
