// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type ServiceMgmtScopeResourceIndex struct {
	References []*ServiceMgmtScopeInformation `json:"references" form:"name=references,json"`
	Scope      *ServiceMgmtScope              `json:"scope" form:"name=scope,json"`
}
