// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type ServiceMgmtMockService struct {
	EnableMock *bool   `json:"enableMock" form:"name=enableMock"`
	RunAsUser  *string `json:"runAsUser" form:"name=runAsUser"`
	Service    *string `json:"service" form:"name=service"`
}
