// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type ServiceMgmtAPIResponseDelete struct {
	APIId          *string `json:"apiId" form:"name=apiId"`
	ErrorReason    *string `json:"errorReason" form:"name=errorReason"`
	ResponseStatus *string `json:"responseStatus" form:"name=responseStatus"` // Response status
}
