// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type ServiceMgmtServiceRegistryPublishGetResponse struct {
	PublishInfo *ServiceMgmtPublishPayload `json:"publishInfo" form:"name=publishInfo,json"`
}
