// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type ServiceMgmtCorrelationIDInfo struct {
	CorrelationId *string `json:"correlationID" form:"name=correlationID"` // The correlation ID of the tracer event which should be archived.
	CreationDate  *int64  `json:"creationDate" form:"name=creationDate"`   // The epoch timestamp (in milliseconds) of the instance when the runtime execution happened.
	Status        *string `json:"status" form:"name=status"`               // The status of the runtime execution. Possible values are SUCCESS, FAILURE
	StatusCode    *int32  `json:"statusCode" form:"name=statusCode"`       // The status code of the runtime execution.
}
