// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type ServiceMgmtXpath struct {
	Namespaces []*ServiceMgmtNamespaces `json:"namespaces" form:"name=namespaces,json"`
	Xpath      *string                  `json:"xpath" form:"name=xpath"`
}
