// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type TransactionMgmtTransactionResponse struct {
	APIId      *string `json:"apiId" form:"name=apiId"`           // API Id
	APIName    *string `json:"apiName" form:"name=apiName"`       // API name
	APIVersion *string `json:"apiVersion" form:"name=apiVersion"` // API version
	Count      *int64  `json:"count" form:"name=count"`           // The total number of invocations based on the provided filter criteria
}
