// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type UserMgmtTeamAdmin struct {
	GroupIDS []*string `json:"groupIds" form:"name=groupIds,json"` // List of groupIds to be assigned as the team administrator. All users in the group will become team administrator.
	UserIDS  []*string `json:"userIds" form:"name=userIds,json"`   // List of userIds to be assigned as the team administrator.
}
