// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package models

type UserMgmtLockedAccounts struct {
	LockedAccounts []*string `json:"lockedAccounts" form:"name=lockedAccounts,json"` // Comma separated list of user accounts which are locked.
}
