// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package enums

// ActionEnum The type of migration action to be performed
type ActionEnum string

const (
	ActionEnumBackup    ActionEnum = "backup"
	ActionEnumClean     ActionEnum = "clean"
	ActionEnumReindex   ActionEnum = "reindex"
	ActionEnumTransform ActionEnum = "transform"
)

func (e ActionEnum) ToPointer() *ActionEnum {
	return &e
}
