// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package enums

// AlgorithmEnum Type of algorithm that needs to be used for signing the JWT
type AlgorithmEnum string

const (
	AlgorithmEnumRs256 AlgorithmEnum = "RS256"
	AlgorithmEnumRs384 AlgorithmEnum = "RS384"
	AlgorithmEnumRs512 AlgorithmEnum = "RS512"
)

func (e AlgorithmEnum) ToPointer() *AlgorithmEnum {
	return &e
}
