// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package enums

// ApprovalEventEnum Type of the approval event
type ApprovalEventEnum string

const (
	ApprovalEventEnumChangeOwner         ApprovalEventEnum = "changeOwner"
	ApprovalEventEnumCreateApplication   ApprovalEventEnum = "createApplication"
	ApprovalEventEnumRegisterApplication ApprovalEventEnum = "registerApplication"
	ApprovalEventEnumSubscribePackage    ApprovalEventEnum = "subscribePackage"
	ApprovalEventEnumUpdateApplication   ApprovalEventEnum = "updateApplication"
)

func (e ApprovalEventEnum) ToPointer() *ApprovalEventEnum {
	return &e
}
