// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package enums

// FtpTypeEnum The type of the FTP proxy server. Applicable only if protocol value is FTP. Indicated by a number in the range 0 to 7. 0 - No proxy, 1 - ftp_user@ftp_host no proxy auth, 2 - ftp_user@ftp_host proxy auth, 3 - site command, 4 - open command, 5 - ftp_user@proxy_user@ftp_host, 6 - proxy_user@ftp_host, 7 - ftp_user@ftp_host proxy_user
type FtpTypeEnum string

const (
	FtpTypeEnumP0 FtpTypeEnum = "0"
	FtpTypeEnumP1 FtpTypeEnum = "1"
	FtpTypeEnumP2 FtpTypeEnum = "2"
	FtpTypeEnumP3 FtpTypeEnum = "3"
	FtpTypeEnumP4 FtpTypeEnum = "4"
	FtpTypeEnumP5 FtpTypeEnum = "5"
	FtpTypeEnumP6 FtpTypeEnum = "6"
	FtpTypeEnumP7 FtpTypeEnum = "7"
)

func (e FtpTypeEnum) ToPointer() *FtpTypeEnum {
	return &e
}
