// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package enums

type MockedConditionParameterEnum string

const (
	MockedConditionParameterEnumBody           MockedConditionParameterEnum = "Body"
	MockedConditionParameterEnumHeader         MockedConditionParameterEnum = "Header"
	MockedConditionParameterEnumQueryParameter MockedConditionParameterEnum = "QueryParameter"
)

func (e MockedConditionParameterEnum) ToPointer() *MockedConditionParameterEnum {
	return &e
}
