// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package enums

// OrderPositionEnum Order of the policy enforcement.   1. First - policy enforcement needs to be added in its respective stage.   2. Last - policy enforcement needs to be added as last in its respective stage.   3. Before First occurrence - Policy needs to be added before the first occurrence of policyTemplateIds specified.   4. After last occurrence - Policy needs to be added after last occurrence of policyTemplateIds specified
type OrderPositionEnum string

const (
	OrderPositionEnumAfterLastOccurence   OrderPositionEnum = "afterLastOccurence"
	OrderPositionEnumBeforeFirstOccurence OrderPositionEnum = "beforeFirstOccurence"
	OrderPositionEnumFirst                OrderPositionEnum = "first"
	OrderPositionEnumLast                 OrderPositionEnum = "last"
)

func (e OrderPositionEnum) ToPointer() *OrderPositionEnum {
	return &e
}
