// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package enums

// RuleTypeEnum Type of the rule
type RuleTypeEnum string

const (
	RuleTypeEnumTeamAssignmentRule RuleTypeEnum = "teamAssignmentRule"
)

func (e RuleTypeEnum) ToPointer() *RuleTypeEnum {
	return &e
}
