openapi: 3.0.1
info:
  title: "availability"
  description: "The purpose of the availability API is to monitor the availability and health status of API Gateway. It provides endpoints for verifying the availabilty of administrative functions, the ability of processing API calls and availability of external services. The responses of the availability API display a status field as the first entry. The status can have the values green, yellow or red describing the overall status of the components to check. This means that when any of the components signals a problem, then the status is set to red. "
  version: "10.11"
servers:
  - url: "http://localhost:5555/rest/apigateway/health/"
paths:
  /health/admin:
    get:
      summary: "Perform administration health check"
      description: "Perform health check for administration parts of API Gateway, such as the UI accessibility and Kibana health."
      responses:
        "200":
          description: "successful operation"
          content:
            "application/json":
              schema: {"$ref": "#/components/schemas/HealthCheckAdminResult"}
              example: "{\"status\":\"green\",\"ui\":{\"status\":\"green\",\"response_time_ms\":\"10\"},\"kibana\":{\"status\":{\"overall\":{\"state\":\"green\",\"nickname\":\"Looking good\",\"icon\":\"success\",\"uiColor\":\"secondary\"}},\"response_time_ms\":\"11\"}}"
        "401":
          description: "This status code indicates that user didn't provide right credentials"
      tags:
        - Availability
  /health/all:
    get:
      summary: "Perform health check for all components of API Gateway"
      description: "Perform health check for all components of API Gateway."
      responses:
        "200":
          description: "successful operation"
          content:
            "application/json":
              schema: {"$ref": "#/components/schemas/HealthCheckAllResult"}
        "401":
          description: "This status code indicates that user didn't provide right credentials"
      tags:
        - Availability
  /health/engine:
    get:
      summary: "Perform core health check"
      description: "Perform health check for core parts of API Gateway, such as Elasticsearch store, cluster environment and Integration Server health."
      responses:
        "200":
          description: "successful operation"
          content:
            "application/json":
              schema: {"$ref": "#/components/schemas/HealthCheckEngineResult"}
              example: "{\"status\":\"green\",\"elasticsearch\":{\"cluster_name\":\"SAG_EventDataStore\",\"status\":\"yellow\"},\"is\":{\"status\":\"green\",\"response_time_ms\":\"30\",\"diskspace\":{\"status\":\"up\"},\"memory\":{\"status\":\"up\",\"freemem\":\"501744736\"}},\"terracotta\":{\"status\":\"green\",\"nodes\":\"1\",\"healthy_nodes\":\"1\",\"response_time_ms\":\"2\"}}"
        "401":
          description: "This status code indicates that user didn't provide right credentials"
      tags:
        - Availability
  /health/externalServices:
    get:
      summary: "Perform health check on all external destinations and resources"
      description: "Perform health check for configured external resources."
      responses:
        "200":
          description: "successful operation"
          content:
            "application/json":
              schema: {"$ref": "#/components/schemas/HealthCheckExternalResult"}
              example: "{\"status\":\"green\",\"destinations\":[{\"type\":\"centrasite\",\"name\":\"centrasite\",\"status\":\"not configured\",\"response_time_ms\":\"0\"},{\"type\":\"centrasite\",\"name\":\"centrasite_snmp\",\"status\":\"not configured\",\"response_time_ms\":\"0\"},{\"type\":\"api_portal\",\"name\":\"api_portal\",\"status\":\"green\",\"response_time_ms\":\"687\"},{\"type\":\"snmp\",\"name\":\"snmp\",\"status\":\"green\",\"response_time_ms\":\"1\"}],\"external_accounts\":[{\"type\":\"service_registry\",\"name\":\"service_registry\",\"status\":\"green\",\"response_time_ms\":\"0\"}]}"
        "401":
          description: "This status code indicates that user didn't provide right credentials"
      tags:
        - Availability
components:
  schemas:
    "HealthCheckAdminResult":
      type: "object"
      properties:
        "kibana":
          type: "object"
          description: "Various values for the Kibana check"
        "status":
          type: "string"
          description: "Either green, yellow or red"
        "ui":
          type: "object"
          description: "Various values for the UI health check"
    "HealthCheckAllResult":
      type: "object"
      properties:
        "admin": {"$ref": "#/components/schemas/HealthCheckAdminResult"}
        "engine": {"$ref": "#/components/schemas/HealthCheckEngineResult"}
        "external": {"$ref": "#/components/schemas/HealthCheckExternalResult"}
    "HealthCheckEngineResult":
      type: "object"
      properties:
        "elasticsearch":
          type: "object"
          description: "Various values for the ElasticSearch check"
        "is":
          type: "object"
          description: "Various values for the Integration Server health check"
        "status":
          type: "string"
          description: "Either green, yellow or red"
        "terracotta":
          type: "object"
          description: "Various values for the Terracotta cluster check"
    "HealthCheckExternalResult":
      type: "object"
      properties:
        "name":
          type: "string"
          description: "The name of the external resource / service"
        "response_time_ms":
          type: "integer"
          description: "Response check time in milli seconds"
        "status":
          type: "string"
          description: "Either green, yellow or red"
        "type":
          type: "string"
          description: "The type of the external resource / service"
