// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * AdminInputLdapConfiguration
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("AdminInputLdapConfiguration")
@JsonPropertyOrder({
    "ldapConfig"
})
@Generated(value = "io.github.primelib.primecodegen")
public class AdminInputLdapConfiguration {

    @JsonProperty("ldapConfig")
    protected AdminLdapconfiguration ldapConfig;

    /**
     * Constructs a validated instance of {@link AdminInputLdapConfiguration}.
     *
     * @param spec the specification to process
     */
    public AdminInputLdapConfiguration(Consumer<AdminInputLdapConfiguration> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link AdminInputLdapConfiguration}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #AdminInputLdapConfiguration(Consumer)} instead.
     * @param ldapConfig ldapConfig
     */
    @ApiStatus.Internal
    public AdminInputLdapConfiguration(AdminLdapconfiguration ldapConfig) {
        this.ldapConfig = ldapConfig;
    }
}
