// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * AdminAgentConfig
 * <p>
 * This defines the Control Plane Agent configuration of API Gateway.
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("AdminAgentConfig")
@JsonPropertyOrder({
    "controlPlaneConfig",
    "enabled",
    "entityId",
    "externalConfig",
    "id",
    "runtimeConfig"
})
@Generated(value = "io.github.primelib.primecodegen")
public class AdminAgentConfig {

    @JsonProperty("controlPlaneConfig")
    protected AdminControlPlaneConfig controlPlaneConfig;

    /**
     * Denotes the communication between API Gateway and Control Plane
     */
    @JsonProperty("enabled")
    protected Boolean enabled;

    @JsonProperty("entityId")
    protected String entityId;

    @JsonProperty("externalConfig")
    protected Boolean externalConfig;

    /**
     * Agent configuration object ID in API Gateway.
     */
    @JsonProperty("id")
    protected String id;

    @JsonProperty("runtimeConfig")
    protected AdminRuntimeConfig runtimeConfig;

    /**
     * Constructs a validated instance of {@link AdminAgentConfig}.
     *
     * @param spec the specification to process
     */
    public AdminAgentConfig(Consumer<AdminAgentConfig> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link AdminAgentConfig}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #AdminAgentConfig(Consumer)} instead.
     * @param controlPlaneConfig controlPlaneConfig
     * @param enabled Denotes the communication between API Gateway and Control Plane
     * @param entityId entityId
     * @param externalConfig externalConfig
     * @param id Agent configuration object ID in API Gateway.
     * @param runtimeConfig runtimeConfig
     */
    @ApiStatus.Internal
    public AdminAgentConfig(AdminControlPlaneConfig controlPlaneConfig, Boolean enabled, String entityId, Boolean externalConfig, String id, AdminRuntimeConfig runtimeConfig) {
        this.controlPlaneConfig = controlPlaneConfig;
        this.enabled = enabled;
        this.entityId = entityId;
        this.externalConfig = externalConfig;
        this.id = id;
        this.runtimeConfig = runtimeConfig;
    }
}
