// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * AdminErrorProcessing
 * <p>
 * Defines the error message configuration. The configured error message will be sent to the invoking client in case API Gateway encounters an exception.
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("AdminErrorProcessing")
@JsonPropertyOrder({
    "defaultErrorMessage",
    "fallbackErrorMessage",
    "sendNativeProviderFault"
})
@Generated(value = "io.github.primelib.primecodegen")
public class AdminErrorProcessing {

    @JsonProperty("defaultErrorMessage")
    protected String defaultErrorMessage;

    @JsonProperty("fallbackErrorMessage")
    protected String fallbackErrorMessage;

    @JsonProperty("sendNativeProviderFault")
    protected String sendNativeProviderFault;

    /**
     * Constructs a validated instance of {@link AdminErrorProcessing}.
     *
     * @param spec the specification to process
     */
    public AdminErrorProcessing(Consumer<AdminErrorProcessing> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link AdminErrorProcessing}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #AdminErrorProcessing(Consumer)} instead.
     * @param defaultErrorMessage defaultErrorMessage
     * @param fallbackErrorMessage fallbackErrorMessage
     * @param sendNativeProviderFault sendNativeProviderFault
     */
    @ApiStatus.Internal
    public AdminErrorProcessing(String defaultErrorMessage, String fallbackErrorMessage, String sendNativeProviderFault) {
        this.defaultErrorMessage = defaultErrorMessage;
        this.fallbackErrorMessage = fallbackErrorMessage;
        this.sendNativeProviderFault = sendNativeProviderFault;
    }
}
