// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * AdminPortalGatewayData
 * <p>
 * This defines the API Portal Gateway data in the API Gateway.
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("AdminPortalGatewayData")
@JsonPropertyOrder({
    "gatewayEndpointsList",
    "microgatewayEndpointsList",
    "portalCommunities"
})
@Generated(value = "io.github.primelib.primecodegen")
public class AdminPortalGatewayData {

    @JsonProperty("gatewayEndpointsList")
    protected List<AdminGatewayEndpoints> gatewayEndpointsList;

    @JsonProperty("microgatewayEndpointsList")
    protected List<AdminGatewayEndpoints> microgatewayEndpointsList;

    /**
     * List of API Portal communities to which APIs should be published.
     */
    @JsonProperty("portalCommunities")
    protected List<AdminPortalCommunities> portalCommunities;

    /**
     * Constructs a validated instance of {@link AdminPortalGatewayData}.
     *
     * @param spec the specification to process
     */
    public AdminPortalGatewayData(Consumer<AdminPortalGatewayData> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link AdminPortalGatewayData}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #AdminPortalGatewayData(Consumer)} instead.
     * @param gatewayEndpointsList gatewayEndpointsList
     * @param microgatewayEndpointsList microgatewayEndpointsList
     * @param portalCommunities List of API Portal communities to which APIs should be published.
     */
    @ApiStatus.Internal
    public AdminPortalGatewayData(List<AdminGatewayEndpoints> gatewayEndpointsList, List<AdminGatewayEndpoints> microgatewayEndpointsList, List<AdminPortalCommunities> portalCommunities) {
        this.gatewayEndpointsList = gatewayEndpointsList;
        this.microgatewayEndpointsList = microgatewayEndpointsList;
        this.portalCommunities = portalCommunities;
    }
}
