// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * AdminMasterPasswordProperties
 * <p>
 * Describes the master password configuration properties in API Gateway
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("AdminMasterPasswordProperties")
@JsonPropertyOrder({
    "daysTilExpire",
    "expireDate",
    "expireInterval",
    "expireMessage",
    "lastChangeDate",
    "statusMessage"
})
@Generated(value = "io.github.primelib.primecodegen")
public class AdminMasterPasswordProperties {

    /**
     * The remaining number of days for the master password expiration
     */
    @JsonProperty("daysTilExpire")
    protected String daysTilExpire;

    /**
     * The expiry date of the master password.The format for this field would be YYYY-MM-DD HH:mm:ssZ
     */
    @JsonProperty("expireDate")
    protected String expireDate;

    /**
     * The interval(in days) after which the master password would expire
     */
    @JsonProperty("expireInterval")
    protected String expireInterval;

    /**
     * The message which will be returned once the master password is expired
     */
    @JsonProperty("expireMessage")
    protected String expireMessage;

    /**
     * The latest date when the master password was updated.The format for this field would be YYYY-MM-DD HH:mm:ssZ
     */
    @JsonProperty("lastChangeDate")
    protected String lastChangeDate;

    /**
     * The current status of the master password
     */
    @JsonProperty("statusMessage")
    protected String statusMessage;

    /**
     * Constructs a validated instance of {@link AdminMasterPasswordProperties}.
     *
     * @param spec the specification to process
     */
    public AdminMasterPasswordProperties(Consumer<AdminMasterPasswordProperties> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link AdminMasterPasswordProperties}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #AdminMasterPasswordProperties(Consumer)} instead.
     * @param daysTilExpire The remaining number of days for the master password expiration
     * @param expireDate The expiry date of the master password.The format for this field would be YYYY-MM-DD HH:mm:ssZ
     * @param expireInterval The interval(in days) after which the master password would expire
     * @param expireMessage The message which will be returned once the master password is expired
     * @param lastChangeDate The latest date when the master password was updated.The format for this field would be YYYY-MM-DD HH:mm:ssZ
     * @param statusMessage The current status of the master password
     */
    @ApiStatus.Internal
    public AdminMasterPasswordProperties(String daysTilExpire, String expireDate, String expireInterval, String expireMessage, String lastChangeDate, String statusMessage) {
        this.daysTilExpire = daysTilExpire;
        this.expireDate = expireDate;
        this.expireInterval = expireInterval;
        this.expireMessage = expireMessage;
        this.lastChangeDate = lastChangeDate;
        this.statusMessage = statusMessage;
    }
}
