// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * AdminMasterPasswordResetResponse
 * <p>
 * Describes the response when the master password is reset
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("AdminMasterPasswordResetResponse")
@JsonPropertyOrder({
    "handleCount",
    "message"
})
@Generated(value = "io.github.primelib.primecodegen")
public class AdminMasterPasswordResetResponse {

    /**
     * The number of passwords that are updated during master password reset
     */
    @JsonProperty("handleCount")
    protected String handleCount;

    /**
     * The response message from the server when the master password is reset
     */
    @JsonProperty("message")
    protected String message;

    /**
     * Constructs a validated instance of {@link AdminMasterPasswordResetResponse}.
     *
     * @param spec the specification to process
     */
    public AdminMasterPasswordResetResponse(Consumer<AdminMasterPasswordResetResponse> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link AdminMasterPasswordResetResponse}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #AdminMasterPasswordResetResponse(Consumer)} instead.
     * @param handleCount The number of passwords that are updated during master password reset
     * @param message The response message from the server when the master password is reset
     */
    @ApiStatus.Internal
    public AdminMasterPasswordResetResponse(String handleCount, String message) {
        this.handleCount = handleCount;
        this.message = message;
    }
}
