// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * AliasLocalIntrospectionConfig
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("AliasLocalIntrospectionConfig")
@JsonPropertyOrder({
    "certificateAlias",
    "description",
    "issuer",
    "jwksuri",
    "trustStoreAlias",
    "useLocalClockSkew"
})
@Generated(value = "io.github.primelib.primecodegen")
public class AliasLocalIntrospectionConfig {

    /**
     * Select the certificate from the truststore that is used to validate the token.
     */
    @JsonProperty("certificateAlias")
    protected String certificateAlias;

    /**
     * Specifies the clock skew in seconds to validate JWT
     */
    @JsonProperty("description")
    protected Integer description;

    /**
     * Third party issuer name
     */
    @JsonProperty("issuer")
    protected String issuer;

    /**
     * JSON Web Key URI
     */
    @JsonProperty("jwksuri")
    protected String jwksuri;

    /**
     * The truststore to be used by API Gateway when validating the token issued by the authorization server. Truststore is a repository that holds all the trusted public certificates
     */
    @JsonProperty("trustStoreAlias")
    protected String trustStoreAlias;

    /**
     * Specifies whether to use the local clock skew for validating JWT.
     */
    @JsonProperty("useLocalClockSkew")
    protected Boolean useLocalClockSkew;

    /**
     * Constructs a validated instance of {@link AliasLocalIntrospectionConfig}.
     *
     * @param spec the specification to process
     */
    public AliasLocalIntrospectionConfig(Consumer<AliasLocalIntrospectionConfig> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link AliasLocalIntrospectionConfig}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #AliasLocalIntrospectionConfig(Consumer)} instead.
     * @param certificateAlias Select the certificate from the truststore that is used to validate the token.
     * @param description Specifies the clock skew in seconds to validate JWT
     * @param issuer Third party issuer name
     * @param jwksuri JSON Web Key URI
     * @param trustStoreAlias The truststore to be used by API Gateway when validating the token issued by the authorization server. Truststore is a repository that holds all the trusted public certificates
     * @param useLocalClockSkew Specifies whether to use the local clock skew for validating JWT.
     */
    @ApiStatus.Internal
    public AliasLocalIntrospectionConfig(String certificateAlias, Integer description, String issuer, String jwksuri, String trustStoreAlias, Boolean useLocalClockSkew) {
        this.certificateAlias = certificateAlias;
        this.description = description;
        this.issuer = issuer;
        this.jwksuri = jwksuri;
        this.trustStoreAlias = trustStoreAlias;
        this.useLocalClockSkew = useLocalClockSkew;
    }
}
