// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * AliasScope
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("AliasScope")
@JsonPropertyOrder({
    "description",
    "name"
})
@Generated(value = "io.github.primelib.primecodegen")
public class AliasScope {

    /**
     * Description of the oauth2 scope
     */
    @JsonProperty("description")
    protected String description;

    /**
     * Name of the oauth2 scope
     */
    @JsonProperty("name")
    protected String name;

    /**
     * Constructs a validated instance of {@link AliasScope}.
     *
     * @param spec the specification to process
     */
    public AliasScope(Consumer<AliasScope> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link AliasScope}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #AliasScope(Consumer)} instead.
     * @param description Description of the oauth2 scope
     * @param name Name of the oauth2 scope
     */
    @ApiStatus.Internal
    public AliasScope(String description, String name) {
        this.description = description;
        this.name = name;
    }
}
