// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * AliasRemoteIntrospectionConfig
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("AliasRemoteIntrospectionConfig")
@JsonPropertyOrder({
    "clientId",
    "clientSecret",
    "introspectionEndpoint",
    "user"
})
@Generated(value = "io.github.primelib.primecodegen")
public class AliasRemoteIntrospectionConfig {

    /**
     * ClientId of a client in the authorization server
     */
    @JsonProperty("clientId")
    protected String clientId;

    @JsonProperty("clientSecret")
    protected AliasGatewaySecret clientSecret;

    /**
     * Endpoint of the authorization server to do the introspection
     */
    @JsonProperty("introspectionEndpoint")
    protected String introspectionEndpoint;

    /**
     * A user in the API Gateway under whom the introspection endpoint is invoked
     */
    @JsonProperty("user")
    protected String user;

    /**
     * Constructs a validated instance of {@link AliasRemoteIntrospectionConfig}.
     *
     * @param spec the specification to process
     */
    public AliasRemoteIntrospectionConfig(Consumer<AliasRemoteIntrospectionConfig> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link AliasRemoteIntrospectionConfig}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #AliasRemoteIntrospectionConfig(Consumer)} instead.
     * @param clientId ClientId of a client in the authorization server
     * @param clientSecret clientSecret
     * @param introspectionEndpoint Endpoint of the authorization server to do the introspection
     * @param user A user in the API Gateway under whom the introspection endpoint is invoked
     */
    @ApiStatus.Internal
    public AliasRemoteIntrospectionConfig(String clientId, AliasGatewaySecret clientSecret, String introspectionEndpoint, String user) {
        this.clientId = clientId;
        this.clientSecret = clientSecret;
        this.introspectionEndpoint = introspectionEndpoint;
        this.user = user;
    }
}
