// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * ApplicationStrategyRequest
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("ApplicationStrategyRequest")
@JsonPropertyOrder({
    "authServerAlias",
    "clientId",
    "clientRegistration",
    "dcrConfig",
    "description",
    "id",
    "name",
    "primaryNode",
    "type"
})
@Generated(value = "io.github.primelib.primecodegen")
public class ApplicationStrategyRequest {

    /**
     * The name of the authorization server alias
     */
    @JsonProperty("authServerAlias")
    protected String authServerAlias;

    /**
     * The client ID for the strategy. This should be provided when the dynamic client registration is not used to generate the credentials for the strategy.
     */
    @JsonProperty("clientId")
    protected String clientId;

    /**
     * Shows the configurations set for the oauth client, when using Dynamic Client Registration. This is a read only model. To update the configuration use the DynamicClientRegistrationConfig model.
     */
    @JsonProperty("clientRegistration")
    protected ApplicationClientRegistration clientRegistration;

    /**
     * Accepts the configurations to be set for the oauth client, when using Dynamic Client Registration
     */
    @JsonProperty("dcrConfig")
    protected ApplicationDynamicClientRegistrationConfig dcrConfig;

    /**
     * The description of the strategy.
     */
    @JsonProperty("description")
    protected String description;

    /**
     * A unique ID for the strategy
     */
    @JsonProperty("id")
    protected String id;

    /**
     * The name of the strategy
     */
    @JsonProperty("name")
    protected String name;

    @JsonProperty("primaryNode")
    protected ApplicationNode primaryNode;

    /**
     * Input file type
     */
    @JsonProperty("type")
    protected String type;

    /**
     * Constructs a validated instance of {@link ApplicationStrategyRequest}.
     *
     * @param spec the specification to process
     */
    public ApplicationStrategyRequest(Consumer<ApplicationStrategyRequest> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link ApplicationStrategyRequest}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #ApplicationStrategyRequest(Consumer)} instead.
     * @param authServerAlias The name of the authorization server alias
     * @param clientId The client ID for the strategy. This should be provided when the dynamic client registration is not used to generate the credentials for the strategy.
     * @param clientRegistration Shows the configurations set for the oauth client, when using Dynamic Client Registration. This is a read only model. To update the configuration use the DynamicClientRegistrationConfig model.
     * @param dcrConfig Accepts the configurations to be set for the oauth client, when using Dynamic Client Registration
     * @param description The description of the strategy.
     * @param id A unique ID for the strategy
     * @param name The name of the strategy
     * @param primaryNode primaryNode
     * @param type Input file type
     */
    @ApiStatus.Internal
    public ApplicationStrategyRequest(String authServerAlias, String clientId, ApplicationClientRegistration clientRegistration, ApplicationDynamicClientRegistrationConfig dcrConfig, String description, String id, String name, ApplicationNode primaryNode, String type) {
        this.authServerAlias = authServerAlias;
        this.clientId = clientId;
        this.clientRegistration = clientRegistration;
        this.dcrConfig = dcrConfig;
        this.description = description;
        this.id = id;
        this.name = name;
        this.primaryNode = primaryNode;
        this.type = type;
    }
}
