// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * ApprovalMgmtApprovalPutRequest
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("ApprovalMgmtApprovalPutRequest")
@JsonPropertyOrder({
    "approverComment"
})
@Generated(value = "io.github.primelib.primecodegen")
public class ApprovalMgmtApprovalPutRequest {

    /**
     * Comment added by the approver
     */
    @JsonProperty("approverComment")
    protected String approverComment;

    /**
     * Constructs a validated instance of {@link ApprovalMgmtApprovalPutRequest}.
     *
     * @param spec the specification to process
     */
    public ApprovalMgmtApprovalPutRequest(Consumer<ApprovalMgmtApprovalPutRequest> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link ApprovalMgmtApprovalPutRequest}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #ApprovalMgmtApprovalPutRequest(Consumer)} instead.
     * @param approverComment Comment added by the approver
     */
    @ApiStatus.Internal
    public ApprovalMgmtApprovalPutRequest(String approverComment) {
        this.approverComment = approverComment;
    }
}
