// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * ApprovalMgmtApprover
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("ApprovalMgmtApprover")
@JsonPropertyOrder({
    "id",
    "name"
})
@Generated(value = "io.github.primelib.primecodegen")
public class ApprovalMgmtApprover {

    @JsonProperty("id")
    protected String id;

    /**
     * Email of the approver
     */
    @JsonProperty("name")
    protected String name;

    /**
     * Constructs a validated instance of {@link ApprovalMgmtApprover}.
     *
     * @param spec the specification to process
     */
    public ApprovalMgmtApprover(Consumer<ApprovalMgmtApprover> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link ApprovalMgmtApprover}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #ApprovalMgmtApprover(Consumer)} instead.
     * @param id id
     * @param name Email of the approver
     */
    @ApiStatus.Internal
    public ApprovalMgmtApprover(String id, String name) {
        this.id = id;
        this.name = name;
    }
}
