// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * ImportExportAPIGatewayAssetsBjson
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("ImportExportAPIGatewayAssetsBjson")
@JsonPropertyOrder({
    "zipFile"
})
@Generated(value = "io.github.primelib.primecodegen")
public class ImportExportAPIGatewayAssetsBjson {

    /**
     * Zip file that contains the API Gateway asset needs to be imported
     */
    @JsonProperty("zipFile")
    protected Byte[] zipFile;

    /**
     * Constructs a validated instance of {@link ImportExportAPIGatewayAssetsBjson}.
     *
     * @param spec the specification to process
     */
    public ImportExportAPIGatewayAssetsBjson(Consumer<ImportExportAPIGatewayAssetsBjson> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link ImportExportAPIGatewayAssetsBjson}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #ImportExportAPIGatewayAssetsBjson(Consumer)} instead.
     * @param zipFile Zip file that contains the API Gateway asset needs to be imported
     */
    @ApiStatus.Internal
    public ImportExportAPIGatewayAssetsBjson(Byte[] zipFile) {
        this.zipFile = zipFile;
    }
}
