// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * InternalServiceOutput
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("InternalServiceOutput")
@JsonPropertyOrder({
    "accessToken",
    "expiresIn",
    "scopes",
    "tokenType"
})
@Generated(value = "io.github.primelib.primecodegen")
public class InternalServiceOutput {

    /**
     * generated access token
     */
    @JsonProperty("accessToken")
    protected String accessToken;

    /**
     * token expiry
     */
    @JsonProperty("expiresIn")
    protected Long expiresIn;

    /**
     * scopes for which the access token is issued
     */
    @JsonProperty("scopes")
    protected String scopes;

    @JsonProperty("tokenType")
    protected String tokenType;

    /**
     * Constructs a validated instance of {@link InternalServiceOutput}.
     *
     * @param spec the specification to process
     */
    public InternalServiceOutput(Consumer<InternalServiceOutput> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link InternalServiceOutput}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #InternalServiceOutput(Consumer)} instead.
     * @param accessToken generated access token
     * @param expiresIn token expiry
     * @param scopes scopes for which the access token is issued
     * @param tokenType tokenType
     */
    @ApiStatus.Internal
    public InternalServiceOutput(String accessToken, Long expiresIn, String scopes, String tokenType) {
        this.accessToken = accessToken;
        this.expiresIn = expiresIn;
        this.scopes = scopes;
        this.tokenType = tokenType;
    }
}
