// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * MonetizationNativeEndpoint
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("MonetizationNativeEndpoint")
@JsonPropertyOrder({
    "description",
    "url"
})
@Generated(value = "io.github.primelib.primecodegen")
public class MonetizationNativeEndpoint {

    /**
     * Endpoint description
     */
    @JsonProperty("description")
    protected String description;

    /**
     * Endpoint URL value
     */
    @JsonProperty("url")
    protected String url;

    /**
     * Constructs a validated instance of {@link MonetizationNativeEndpoint}.
     *
     * @param spec the specification to process
     */
    public MonetizationNativeEndpoint(Consumer<MonetizationNativeEndpoint> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link MonetizationNativeEndpoint}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #MonetizationNativeEndpoint(Consumer)} instead.
     * @param description Endpoint description
     * @param url Endpoint URL value
     */
    @ApiStatus.Internal
    public MonetizationNativeEndpoint(String description, String url) {
        this.description = description;
        this.url = url;
    }
}
