// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Map;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * MonetizationCallback
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("MonetizationCallback")
@JsonPropertyOrder({
    "callbacksMap",
    "getref",
    "vendorExtensions"
})
@Generated(value = "io.github.primelib.primecodegen")
public class MonetizationCallback {

    /**
     * A Path Item Object used to define a callback request and expected responses
     */
    @JsonProperty("callbacksMap")
    protected Map<String, ServiceMgmtPath> callbacksMap;

    @JsonProperty("get$ref")
    protected String getref;

    @JsonProperty("vendorExtensions")
    protected Map<String, Object> vendorExtensions;

    /**
     * Constructs a validated instance of {@link MonetizationCallback}.
     *
     * @param spec the specification to process
     */
    public MonetizationCallback(Consumer<MonetizationCallback> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link MonetizationCallback}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #MonetizationCallback(Consumer)} instead.
     * @param callbacksMap A Path Item Object used to define a callback request and expected responses
     * @param getref getref
     * @param vendorExtensions vendorExtensions
     */
    @ApiStatus.Internal
    public MonetizationCallback(Map<String, ServiceMgmtPath> callbacksMap, String getref, Map<String, Object> vendorExtensions) {
        this.callbacksMap = callbacksMap;
        this.getref = getref;
        this.vendorExtensions = vendorExtensions;
    }
}
