// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Map;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * MonetizationEntitySet
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("MonetizationEntitySet")
@JsonPropertyOrder({
    "enabled",
    "entityType",
    "parameters"
})
@Generated(value = "io.github.primelib.primecodegen")
public class MonetizationEntitySet {

    @JsonProperty("enabled")
    protected Boolean enabled;

    @JsonProperty("entityType")
    protected String entityType;

    @JsonProperty("parameters")
    protected Map<String, String> parameters;

    /**
     * Constructs a validated instance of {@link MonetizationEntitySet}.
     *
     * @param spec the specification to process
     */
    public MonetizationEntitySet(Consumer<MonetizationEntitySet> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link MonetizationEntitySet}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #MonetizationEntitySet(Consumer)} instead.
     * @param enabled enabled
     * @param entityType entityType
     * @param parameters parameters
     */
    @ApiStatus.Internal
    public MonetizationEntitySet(Boolean enabled, String entityType, Map<String, String> parameters) {
        this.enabled = enabled;
        this.entityType = entityType;
        this.parameters = parameters;
    }
}
