// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Map;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * MonetizationOauthFlows
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("MonetizationOauthFlows")
@JsonPropertyOrder({
    "authorizationCode",
    "clientCredentials",
    "implicit",
    "password",
    "vendorExtensions"
})
@Generated(value = "io.github.primelib.primecodegen")
public class MonetizationOauthFlows {

    @JsonProperty("authorizationCode")
    protected MonetizationOauth2Definition authorizationCode;

    @JsonProperty("clientCredentials")
    protected MonetizationOauth2Definition clientCredentials;

    @JsonProperty("implicit")
    protected MonetizationOauth2Definition implicit;

    @JsonProperty("password")
    protected MonetizationOauth2Definition password;

    @JsonProperty("vendorExtensions")
    protected Map<String, Object> vendorExtensions;

    /**
     * Constructs a validated instance of {@link MonetizationOauthFlows}.
     *
     * @param spec the specification to process
     */
    public MonetizationOauthFlows(Consumer<MonetizationOauthFlows> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link MonetizationOauthFlows}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #MonetizationOauthFlows(Consumer)} instead.
     * @param authorizationCode authorizationCode
     * @param clientCredentials clientCredentials
     * @param implicit implicit
     * @param password password
     * @param vendorExtensions vendorExtensions
     */
    @ApiStatus.Internal
    public MonetizationOauthFlows(MonetizationOauth2Definition authorizationCode, MonetizationOauth2Definition clientCredentials, MonetizationOauth2Definition implicit, MonetizationOauth2Definition password, Map<String, Object> vendorExtensions) {
        this.authorizationCode = authorizationCode;
        this.clientCredentials = clientCredentials;
        this.implicit = implicit;
        this.password = password;
        this.vendorExtensions = vendorExtensions;
    }
}
