// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * MonetizationSubscriptionUpdateRequest
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("MonetizationSubscriptionUpdateRequest")
@JsonPropertyOrder({
    "newPackageId",
    "newPlanId",
    "requesterComment",
    "requesterName"
})
@Generated(value = "io.github.primelib.primecodegen")
public class MonetizationSubscriptionUpdateRequest {

    /**
     * Package id to which the subscription needs to be switched
     */
    @JsonProperty("newPackageId")
    protected String newPackageId;

    /**
     * Plan id to which the subscription needs to be switched
     */
    @JsonProperty("newPlanId")
    protected String newPlanId;

    /**
     * Requester comment to use in the update subscription approval request.
     */
    @JsonProperty("requesterComment")
    protected String requesterComment;

    /**
     * Name of the requester to whom the subscription is requested. This will be used as requester name in update subscription approval request. If not specified the name of the invoking user will be used in approval request
     */
    @JsonProperty("requesterName")
    protected String requesterName;

    /**
     * Constructs a validated instance of {@link MonetizationSubscriptionUpdateRequest}.
     *
     * @param spec the specification to process
     */
    public MonetizationSubscriptionUpdateRequest(Consumer<MonetizationSubscriptionUpdateRequest> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link MonetizationSubscriptionUpdateRequest}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #MonetizationSubscriptionUpdateRequest(Consumer)} instead.
     * @param newPackageId Package id to which the subscription needs to be switched
     * @param newPlanId Plan id to which the subscription needs to be switched
     * @param requesterComment Requester comment to use in the update subscription approval request.
     * @param requesterName Name of the requester to whom the subscription is requested. This will be used as requester name in update subscription approval request. If not specified the name of the invoking user will be used in approval request
     */
    @ApiStatus.Internal
    public MonetizationSubscriptionUpdateRequest(String newPackageId, String newPlanId, String requesterComment, String requesterName) {
        this.newPackageId = newPackageId;
        this.newPlanId = newPlanId;
        this.requesterComment = requesterComment;
        this.requesterName = requesterName;
    }
}
