// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Map;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * MonetizationServer
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("MonetizationServer")
@JsonPropertyOrder({
    "description",
    "url",
    "variables",
    "vendorExtensions"
})
@Generated(value = "io.github.primelib.primecodegen")
public class MonetizationServer {

    /**
     * An optional string describing the host designated by the URL
     */
    @JsonProperty("description")
    protected String description;

    /**
     * A URL to the target host. This URL supports Server Variables and MAY be relative, to indicate that the host location is relative to the location where the OpenAPI document is being served. Variable substitutions will be made when a variable is named in {brackets}
     */
    @JsonProperty("url")
    protected String url;

    /**
     * A map between a variable name and its value. The value is used for substitution in the server's URL template
     */
    @JsonProperty("variables")
    protected Map<String, ServiceMgmtServerVariable> variables;

    @JsonProperty("vendorExtensions")
    protected Map<String, Object> vendorExtensions;

    /**
     * Constructs a validated instance of {@link MonetizationServer}.
     *
     * @param spec the specification to process
     */
    public MonetizationServer(Consumer<MonetizationServer> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link MonetizationServer}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #MonetizationServer(Consumer)} instead.
     * @param description An optional string describing the host designated by the URL
     * @param url A URL to the target host. This URL supports Server Variables and MAY be relative, to indicate that the host location is relative to the location where the OpenAPI document is being served. Variable substitutions will be made when a variable is named in {brackets}
     * @param variables A map between a variable name and its value. The value is used for substitution in the server's URL template
     * @param vendorExtensions vendorExtensions
     */
    @ApiStatus.Internal
    public MonetizationServer(String description, String url, Map<String, ServiceMgmtServerVariable> variables, Map<String, Object> vendorExtensions) {
        this.description = description;
        this.url = url;
        this.variables = variables;
        this.vendorExtensions = vendorExtensions;
    }
}
