// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * MonetizationGqlArgument
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("MonetizationGqlArgument")
@JsonPropertyOrder({
    "comments",
    "name",
    "value"
})
@Generated(value = "io.github.primelib.primecodegen")
public class MonetizationGqlArgument {

    /**
     * List of comments
     */
    @JsonProperty("comments")
    protected List<MonetizationGqlComment> comments;

    /**
     * Name of the argument
     */
    @JsonProperty("name")
    protected String name;

    @JsonProperty("value")
    protected MonetizationGqlValue value;

    /**
     * Constructs a validated instance of {@link MonetizationGqlArgument}.
     *
     * @param spec the specification to process
     */
    public MonetizationGqlArgument(Consumer<MonetizationGqlArgument> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link MonetizationGqlArgument}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #MonetizationGqlArgument(Consumer)} instead.
     * @param comments List of comments
     * @param name Name of the argument
     * @param value value
     */
    @ApiStatus.Internal
    public MonetizationGqlArgument(List<MonetizationGqlComment> comments, String name, MonetizationGqlValue value) {
        this.comments = comments;
        this.name = name;
        this.value = value;
    }
}
