// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Map;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * MonetizationInfo
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("MonetizationInfo")
@JsonPropertyOrder({
    "contact",
    "description",
    "license",
    "termsOfService",
    "title",
    "vendorExtensions",
    "version"
})
@Generated(value = "io.github.primelib.primecodegen")
public class MonetizationInfo {

    @JsonProperty("contact")
    protected MonetizationContact contact;

    /**
     * A short description of the application
     */
    @JsonProperty("description")
    protected String description;

    @JsonProperty("license")
    protected MonetizationLicence license;

    /**
     * A URL to the Terms of Service for the API
     */
    @JsonProperty("termsOfService")
    protected String termsOfService;

    /**
     * The title of the application
     */
    @JsonProperty("title")
    protected String title;

    @JsonProperty("vendorExtensions")
    protected Map<String, Object> vendorExtensions;

    /**
     * Version of the API
     */
    @JsonProperty("version")
    protected String version;

    /**
     * Constructs a validated instance of {@link MonetizationInfo}.
     *
     * @param spec the specification to process
     */
    public MonetizationInfo(Consumer<MonetizationInfo> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link MonetizationInfo}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #MonetizationInfo(Consumer)} instead.
     * @param contact contact
     * @param description A short description of the application
     * @param license license
     * @param termsOfService A URL to the Terms of Service for the API
     * @param title The title of the application
     * @param vendorExtensions vendorExtensions
     * @param version Version of the API
     */
    @ApiStatus.Internal
    public MonetizationInfo(MonetizationContact contact, String description, MonetizationLicence license, String termsOfService, String title, Map<String, Object> vendorExtensions, String version) {
        this.contact = contact;
        this.description = description;
        this.license = license;
        this.termsOfService = termsOfService;
        this.title = title;
        this.vendorExtensions = vendorExtensions;
        this.version = version;
    }
}
