// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * MonetizationGqlComment
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("MonetizationGqlComment")
@JsonPropertyOrder({
    "content"
})
@Generated(value = "io.github.primelib.primecodegen")
public class MonetizationGqlComment {

    /**
     * Comment value
     */
    @JsonProperty("content")
    protected String content;

    /**
     * Constructs a validated instance of {@link MonetizationGqlComment}.
     *
     * @param spec the specification to process
     */
    public MonetizationGqlComment(Consumer<MonetizationGqlComment> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link MonetizationGqlComment}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #MonetizationGqlComment(Consumer)} instead.
     * @param content Comment value
     */
    @ApiStatus.Internal
    public MonetizationGqlComment(String content) {
        this.content = content;
    }
}
