// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * MonetizationUsage
 * <p>
 * This is used to show the current usage of a subscription for the current tenure
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("MonetizationUsage")
@JsonPropertyOrder({
    "applicationId",
    "applicationName",
    "configuredQuota",
    "endTime",
    "failureCount",
    "interval",
    "intervalUnit",
    "packageId",
    "packageName",
    "planId",
    "planName",
    "quotaAllowed",
    "remainingPeriod",
    "remainingPeriodInMillis",
    "restoredIntervalInSeconds",
    "startDayOfTheWeek",
    "startTime",
    "successCount",
    "usedQuota"
})
@Generated(value = "io.github.primelib.primecodegen")
public class MonetizationUsage {

    /**
     * Application id of the subscription
     */
    @JsonProperty("applicationId")
    protected String applicationId;

    /**
     * Application name of the subscription
     */
    @JsonProperty("applicationName")
    protected String applicationName;

    /**
     * Quota (number of invokes) of the subscription as text for the current interval
     */
    @JsonProperty("configuredQuota")
    protected String configuredQuota;

    /**
     * End time of the subscription in milli seconds for the current interval
     */
    @JsonProperty("endTime")
    protected Long endTime;

    /**
     * This will show the number of failure invokes for the current subscription in the current interval
     */
    @JsonProperty("failureCount")
    protected Integer failureCount;

    /**
     * Interval value of the subscription for current interval
     */
    @JsonProperty("interval")
    protected String interval;

    /**
     * Interval Unit of the subscription for the current interval
     */
    @JsonProperty("intervalUnit")
    protected String intervalUnit;

    /**
     * Package id of the subscription
     */
    @JsonProperty("packageId")
    protected String packageId;

    /**
     * Package name of the subscription
     */
    @JsonProperty("packageName")
    protected String packageName;

    /**
     * Plan id of the subscription
     */
    @JsonProperty("planId")
    protected String planId;

    /**
     * Plan name of the subscription
     */
    @JsonProperty("planName")
    protected String planName;

    /**
     * Quota (number of invokes) allowed for the subscription for current interval
     */
    @JsonProperty("quotaAllowed")
    protected Long quotaAllowed;

    /**
     * Remaining period of the subscription as text for the current interval
     */
    @JsonProperty("remainingPeriod")
    protected String remainingPeriod;

    /**
     * Remaining period of the subscription in milli seconds for the current interval
     */
    @JsonProperty("remainingPeriodInMillis")
    protected Long remainingPeriodInMillis;

    /**
     * This value shows the elapses time of subscription in case of restart of the server. This end time and remaining time will be calculated based on start time, interval and restored interval.
     */
    @JsonProperty("restoredIntervalInSeconds")
    protected Integer restoredIntervalInSeconds;

    /**
     * Start of the week configured in API gateway
     */
    @JsonProperty("startDayOfTheWeek")
    protected String startDayOfTheWeek;

    /**
     * Start time of the subscription for current interval in milli seconds
     */
    @JsonProperty("startTime")
    protected Long startTime;

    /**
     * This will show the number of successful invokes for the current subscription in the current interval
     */
    @JsonProperty("successCount")
    protected Integer successCount;

    /**
     * Quota (number of invokes) used count for the subscription for current interval
     */
    @JsonProperty("usedQuota")
    protected Long usedQuota;

    /**
     * Constructs a validated instance of {@link MonetizationUsage}.
     *
     * @param spec the specification to process
     */
    public MonetizationUsage(Consumer<MonetizationUsage> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link MonetizationUsage}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #MonetizationUsage(Consumer)} instead.
     * @param applicationId Application id of the subscription
     * @param applicationName Application name of the subscription
     * @param configuredQuota Quota (number of invokes) of the subscription as text for the current interval
     * @param endTime End time of the subscription in milli seconds for the current interval
     * @param failureCount This will show the number of failure invokes for the current subscription in the current interval
     * @param interval Interval value of the subscription for current interval
     * @param intervalUnit Interval Unit of the subscription for the current interval
     * @param packageId Package id of the subscription
     * @param packageName Package name of the subscription
     * @param planId Plan id of the subscription
     * @param planName Plan name of the subscription
     * @param quotaAllowed Quota (number of invokes) allowed for the subscription for current interval
     * @param remainingPeriod Remaining period of the subscription as text for the current interval
     * @param remainingPeriodInMillis Remaining period of the subscription in milli seconds for the current interval
     * @param restoredIntervalInSeconds This value shows the elapses time of subscription in case of restart of the server. This end time and remaining time will be calculated based on start time, interval and restored interval.
     * @param startDayOfTheWeek Start of the week configured in API gateway
     * @param startTime Start time of the subscription for current interval in milli seconds
     * @param successCount This will show the number of successful invokes for the current subscription in the current interval
     * @param usedQuota Quota (number of invokes) used count for the subscription for current interval
     */
    @ApiStatus.Internal
    public MonetizationUsage(String applicationId, String applicationName, String configuredQuota, Long endTime, Integer failureCount, String interval, String intervalUnit, String packageId, String packageName, String planId, String planName, Long quotaAllowed, String remainingPeriod, Long remainingPeriodInMillis, Integer restoredIntervalInSeconds, String startDayOfTheWeek, Long startTime, Integer successCount, Long usedQuota) {
        this.applicationId = applicationId;
        this.applicationName = applicationName;
        this.configuredQuota = configuredQuota;
        this.endTime = endTime;
        this.failureCount = failureCount;
        this.interval = interval;
        this.intervalUnit = intervalUnit;
        this.packageId = packageId;
        this.packageName = packageName;
        this.planId = planId;
        this.planName = planName;
        this.quotaAllowed = quotaAllowed;
        this.remainingPeriod = remainingPeriod;
        this.remainingPeriodInMillis = remainingPeriodInMillis;
        this.restoredIntervalInSeconds = restoredIntervalInSeconds;
        this.startDayOfTheWeek = startDayOfTheWeek;
        this.startTime = startTime;
        this.successCount = successCount;
        this.usedQuota = usedQuota;
    }
}
