// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * PolicyMgmtInternationalizedString
 * <p>
 * This model is used to store a string with its corresponding locale
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("PolicyMgmtInternationalizedString")
@JsonPropertyOrder({
    "locale",
    "value"
})
@Generated(value = "io.github.primelib.primecodegen")
public class PolicyMgmtInternationalizedString {

    /**
     * This property will have the localization information of the property 'value'.
     */
    @JsonProperty("locale")
    protected String locale;

    /**
     * This property will hold the actual string
     */
    @JsonProperty("value")
    protected String value;

    /**
     * Constructs a validated instance of {@link PolicyMgmtInternationalizedString}.
     *
     * @param spec the specification to process
     */
    public PolicyMgmtInternationalizedString(Consumer<PolicyMgmtInternationalizedString> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link PolicyMgmtInternationalizedString}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #PolicyMgmtInternationalizedString(Consumer)} instead.
     * @param locale This property will have the localization information of the property 'value'.
     * @param value This property will hold the actual string
     */
    @ApiStatus.Internal
    public PolicyMgmtInternationalizedString(String locale, String value) {
        this.locale = locale;
        this.value = value;
    }
}
