// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * PolicyMgmtPolicyEnforcements
 * <p>
 * This model contains the list of policy action id specific to a stage.
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("PolicyMgmtPolicyEnforcements")
@JsonPropertyOrder({
    "enforcements",
    "stageKey"
})
@Generated(value = "io.github.primelib.primecodegen")
public class PolicyMgmtPolicyEnforcements {

    @JsonProperty("enforcements")
    protected List<PolicyMgmtEnforcement> enforcements;

    /**
     * Policy stage. User can refer resource /policyStages to get the list stages can be added here
     */
    @JsonProperty("stageKey")
    protected String stageKey;

    /**
     * Constructs a validated instance of {@link PolicyMgmtPolicyEnforcements}.
     *
     * @param spec the specification to process
     */
    public PolicyMgmtPolicyEnforcements(Consumer<PolicyMgmtPolicyEnforcements> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link PolicyMgmtPolicyEnforcements}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #PolicyMgmtPolicyEnforcements(Consumer)} instead.
     * @param enforcements enforcements
     * @param stageKey Policy stage. User can refer resource /policyStages to get the list stages can be added here
     */
    @ApiStatus.Internal
    public PolicyMgmtPolicyEnforcements(List<PolicyMgmtEnforcement> enforcements, String stageKey) {
        this.enforcements = enforcements;
        this.stageKey = stageKey;
    }
}
