// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * PolicyMgmtAssertionConfiguration
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("PolicyMgmtAssertionConfiguration")
@JsonPropertyOrder({
    "assertionElement",
    "assertionName",
    "assertionType",
    "assertionId"
})
@Generated(value = "io.github.primelib.primecodegen")
public class PolicyMgmtAssertionConfiguration {

    /**
     * XML element which represents the assertion
     */
    @JsonProperty("Assertion element")
    protected String assertionElement;

    /**
     * Name of the assertion
     */
    @JsonProperty("Assertion name")
    protected String assertionName;

    /**
     * Type of assertion(tokenAssertion/bindingAssertion)
     */
    @JsonProperty("Assertion type")
    protected String assertionType;

    /**
     * A unique ID for the assertion
     */
    @JsonProperty("assertionId")
    protected String assertionId;

    /**
     * Constructs a validated instance of {@link PolicyMgmtAssertionConfiguration}.
     *
     * @param spec the specification to process
     */
    public PolicyMgmtAssertionConfiguration(Consumer<PolicyMgmtAssertionConfiguration> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link PolicyMgmtAssertionConfiguration}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #PolicyMgmtAssertionConfiguration(Consumer)} instead.
     * @param assertionElement XML element which represents the assertion
     * @param assertionName Name of the assertion
     * @param assertionType Type of assertion(tokenAssertion/bindingAssertion)
     * @param assertionId A unique ID for the assertion
     */
    @ApiStatus.Internal
    public PolicyMgmtAssertionConfiguration(String assertionElement, String assertionName, String assertionType, String assertionId) {
        this.assertionElement = assertionElement;
        this.assertionName = assertionName;
        this.assertionType = assertionType;
        this.assertionId = assertionId;
    }
}
