// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * PolicyMgmtMobileApplicationConfiguration
 * <p>
 * Configured values are used in Threat protection Rules 'Mobile App filter'
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("PolicyMgmtMobileApplicationConfiguration")
@JsonPropertyOrder({
    "mobileAppDeviceTypes",
    "mobileApplications"
})
@Generated(value = "io.github.primelib.primecodegen")
public class PolicyMgmtMobileApplicationConfiguration {

    /**
     * Configure Device Types to be filtered when Threat protection 'Mobile App Filter' Rule enforced
     */
    @JsonProperty("mobileAppDeviceTypes")
    protected List<String> mobileAppDeviceTypes;

    /**
     * Configure Mobile Application names to be filtered when Threat protection 'Mobile App Filter' Rule enforced
     */
    @JsonProperty("mobileApplications")
    protected List<String> mobileApplications;

    /**
     * Constructs a validated instance of {@link PolicyMgmtMobileApplicationConfiguration}.
     *
     * @param spec the specification to process
     */
    public PolicyMgmtMobileApplicationConfiguration(Consumer<PolicyMgmtMobileApplicationConfiguration> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link PolicyMgmtMobileApplicationConfiguration}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #PolicyMgmtMobileApplicationConfiguration(Consumer)} instead.
     * @param mobileAppDeviceTypes Configure Device Types to be filtered when Threat protection 'Mobile App Filter' Rule enforced
     * @param mobileApplications Configure Mobile Application names to be filtered when Threat protection 'Mobile App Filter' Rule enforced
     */
    @ApiStatus.Internal
    public PolicyMgmtMobileApplicationConfiguration(List<String> mobileAppDeviceTypes, List<String> mobileApplications) {
        this.mobileAppDeviceTypes = mobileAppDeviceTypes;
        this.mobileApplications = mobileApplications;
    }
}
