// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * PortMgmtIpaccessModeHostsList
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("PortMgmtIpaccessModeHostsList")
@JsonPropertyOrder({
    "hostsList"
})
@Generated(value = "io.github.primelib.primecodegen")
public class PortMgmtIpaccessModeHostsList {

    @JsonProperty("hostsList")
    protected List<String> hostsList;

    /**
     * Constructs a validated instance of {@link PortMgmtIpaccessModeHostsList}.
     *
     * @param spec the specification to process
     */
    public PortMgmtIpaccessModeHostsList(Consumer<PortMgmtIpaccessModeHostsList> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link PortMgmtIpaccessModeHostsList}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #PortMgmtIpaccessModeHostsList(Consumer)} instead.
     * @param hostsList hostsList
     */
    @ApiStatus.Internal
    public PortMgmtIpaccessModeHostsList(List<String> hostsList) {
        this.hostsList = hostsList;
    }
}
