// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * PromotionMgmtRollback
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("PromotionMgmtRollback")
@JsonPropertyOrder({
    "description",
    "id",
    "includeRegisteredApplications",
    "lastRollbackTime",
    "name",
    "promotedBy",
    "promotionId",
    "promotionTime",
    "sourceStage",
    "status"
})
@Generated(value = "io.github.primelib.primecodegen")
public class PromotionMgmtRollback {

    /**
     * Description for the rollback
     */
    @JsonProperty("description")
    protected String description;

    @JsonProperty("id")
    protected String id;

    /**
     * Whether RegisteredApplications are included
     */
    @JsonProperty("includeRegisteredApplications")
    protected Boolean includeRegisteredApplications;

    /**
     * The time at which the asset promotion was rolled back
     */
    @JsonProperty("lastRollbackTime")
    protected String lastRollbackTime;

    /**
     * Name for the rollback
     */
    @JsonProperty("name")
    protected String name;

    /**
     * User who initiated the promotion
     */
    @JsonProperty("promotedBy")
    protected String promotedBy;

    /**
     * Id of the promotion to map the rollback with the promotion from the source stage
     */
    @JsonProperty("promotionId")
    protected String promotionId;

    /**
     * Actual time of the promotion
     */
    @JsonProperty("promotionTime")
    protected String promotionTime;

    /**
     * Source stage of the promotion
     */
    @JsonProperty("sourceStage")
    protected String sourceStage;

    /**
     * Overall status of the rollback whether it's success or failure
     */
    @JsonProperty("status")
    protected String status;

    /**
     * Constructs a validated instance of {@link PromotionMgmtRollback}.
     *
     * @param spec the specification to process
     */
    public PromotionMgmtRollback(Consumer<PromotionMgmtRollback> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link PromotionMgmtRollback}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #PromotionMgmtRollback(Consumer)} instead.
     * @param description Description for the rollback
     * @param id id
     * @param includeRegisteredApplications Whether RegisteredApplications are included
     * @param lastRollbackTime The time at which the asset promotion was rolled back
     * @param name Name for the rollback
     * @param promotedBy User who initiated the promotion
     * @param promotionId Id of the promotion to map the rollback with the promotion from the source stage
     * @param promotionTime Actual time of the promotion
     * @param sourceStage Source stage of the promotion
     * @param status Overall status of the rollback whether it's success or failure
     */
    @ApiStatus.Internal
    public PromotionMgmtRollback(String description, String id, Boolean includeRegisteredApplications, String lastRollbackTime, String name, String promotedBy, String promotionId, String promotionTime, String sourceStage, String status) {
        this.description = description;
        this.id = id;
        this.includeRegisteredApplications = includeRegisteredApplications;
        this.lastRollbackTime = lastRollbackTime;
        this.name = name;
        this.promotedBy = promotedBy;
        this.promotionId = promotionId;
        this.promotionTime = promotionTime;
        this.sourceStage = sourceStage;
        this.status = status;
    }
}
