// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * SalesInformation
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("SalesInformation")
@JsonPropertyOrder({
    "autoCallHome",
    "contractDetails",
    "contractPosNumber",
    "customerId",
    "customerName",
    "licenseKey",
    "licenseTypeDetails",
    "serialNumber"
})
@Generated(value = "io.github.primelib.primecodegen")
public class SalesInformation {

    @JsonProperty("AutoCallHome")
    protected String autoCallHome;

    @JsonProperty("ContractDetails")
    protected String contractDetails;

    @JsonProperty("ContractPosNumber")
    protected String contractPosNumber;

    @JsonProperty("Customer ID")
    protected String customerId;

    @JsonProperty("Customer Name")
    protected String customerName;

    @JsonProperty("License Key")
    protected String licenseKey;

    @JsonProperty("License Type Details")
    protected String licenseTypeDetails;

    @JsonProperty("Serial Number")
    protected String serialNumber;

    /**
     * Constructs a validated instance of {@link SalesInformation}.
     *
     * @param spec the specification to process
     */
    public SalesInformation(Consumer<SalesInformation> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link SalesInformation}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #SalesInformation(Consumer)} instead.
     * @param autoCallHome autoCallHome
     * @param contractDetails contractDetails
     * @param contractPosNumber contractPosNumber
     * @param customerId customerId
     * @param customerName customerName
     * @param licenseKey licenseKey
     * @param licenseTypeDetails licenseTypeDetails
     * @param serialNumber serialNumber
     */
    @ApiStatus.Internal
    public SalesInformation(String autoCallHome, String contractDetails, String contractPosNumber, String customerId, String customerName, String licenseKey, String licenseTypeDetails, String serialNumber) {
        this.autoCallHome = autoCallHome;
        this.contractDetails = contractDetails;
        this.contractPosNumber = contractPosNumber;
        this.customerId = customerId;
        this.customerName = customerName;
        this.licenseKey = licenseKey;
        this.licenseTypeDetails = licenseTypeDetails;
        this.serialNumber = serialNumber;
    }
}
