// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * ServiceMgmtAPIResponseModel
 * <p>
 * This model contains the basics details of an API.
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("ServiceMgmtAPIResponseModel")
@JsonPropertyOrder({
    "api",
    "responseStatus"
})
@Generated(value = "io.github.primelib.primecodegen")
public class ServiceMgmtAPIResponseModel {

    /**
     * This model contains the basics details of an API.
     */
    @JsonProperty("api")
    protected ServiceMgmtAPIResponseGetAPIS api;

    /**
     * Response status
     */
    @JsonProperty("responseStatus")
    protected String responseStatus;

    /**
     * Constructs a validated instance of {@link ServiceMgmtAPIResponseModel}.
     *
     * @param spec the specification to process
     */
    public ServiceMgmtAPIResponseModel(Consumer<ServiceMgmtAPIResponseModel> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link ServiceMgmtAPIResponseModel}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #ServiceMgmtAPIResponseModel(Consumer)} instead.
     * @param api This model contains the basics details of an API.
     * @param responseStatus Response status
     */
    @ApiStatus.Internal
    public ServiceMgmtAPIResponseModel(ServiceMgmtAPIResponseGetAPIS api, String responseStatus) {
        this.api = api;
        this.responseStatus = responseStatus;
    }
}
