// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * ServiceMgmtUnpublishInfo
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("ServiceMgmtUnpublishInfo")
@JsonPropertyOrder({
    "apiId",
    "serviceRegistryIds"
})
@Generated(value = "io.github.primelib.primecodegen")
public class ServiceMgmtUnpublishInfo {

    /**
     * API id for the API to be unpublished. This field is required.
     */
    @JsonProperty("apiId")
    protected String apiId;

    /**
     * List of ids of the service registries from which the API has to be unpublished. This field is required.
     */
    @JsonProperty("serviceRegistryIds")
    protected List<String> serviceRegistryIds;

    /**
     * Constructs a validated instance of {@link ServiceMgmtUnpublishInfo}.
     *
     * @param spec the specification to process
     */
    public ServiceMgmtUnpublishInfo(Consumer<ServiceMgmtUnpublishInfo> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link ServiceMgmtUnpublishInfo}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #ServiceMgmtUnpublishInfo(Consumer)} instead.
     * @param apiId API id for the API to be unpublished. This field is required.
     * @param serviceRegistryIds List of ids of the service registries from which the API has to be unpublished. This field is required.
     */
    @ApiStatus.Internal
    public ServiceMgmtUnpublishInfo(String apiId, List<String> serviceRegistryIds) {
        this.apiId = apiId;
        this.serviceRegistryIds = serviceRegistryIds;
    }
}
