// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Map;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * ServiceMgmtPart
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("ServiceMgmtPart")
@JsonPropertyOrder({
    "allHeaders",
    "content",
    "contentType",
    "dataHandler",
    "description",
    "disposition",
    "fileName",
    "inputStream",
    "lineCount",
    "size"
})
@Generated(value = "io.github.primelib.primecodegen")
public class ServiceMgmtPart {

    @JsonProperty("allHeaders")
    protected Object allHeaders;

    /**
     * A map containing descriptions of potential response payloads. The key is a media type or media type range and the value describes it
     */
    @JsonProperty("content")
    protected Map<String, ServiceMgmtMediaType> content;

    @JsonProperty("contentType")
    protected String contentType;

    @JsonProperty("dataHandler")
    protected ServiceMgmtDataHandler dataHandler;

    @JsonProperty("description")
    protected String description;

    @JsonProperty("disposition")
    protected String disposition;

    @JsonProperty("fileName")
    protected String fileName;

    @JsonProperty("inputStream")
    protected Object inputStream;

    @JsonProperty("lineCount")
    protected Integer lineCount;

    @JsonProperty("size")
    protected Integer size;

    /**
     * Constructs a validated instance of {@link ServiceMgmtPart}.
     *
     * @param spec the specification to process
     */
    public ServiceMgmtPart(Consumer<ServiceMgmtPart> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link ServiceMgmtPart}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #ServiceMgmtPart(Consumer)} instead.
     * @param allHeaders allHeaders
     * @param content A map containing descriptions of potential response payloads. The key is a media type or media type range and the value describes it
     * @param contentType contentType
     * @param dataHandler dataHandler
     * @param description description
     * @param disposition disposition
     * @param fileName fileName
     * @param inputStream inputStream
     * @param lineCount lineCount
     * @param size size
     */
    @ApiStatus.Internal
    public ServiceMgmtPart(Object allHeaders, Map<String, ServiceMgmtMediaType> content, String contentType, ServiceMgmtDataHandler dataHandler, String description, String disposition, String fileName, Object inputStream, Integer lineCount, Integer size) {
        this.allHeaders = allHeaders;
        this.content = content;
        this.contentType = contentType;
        this.dataHandler = dataHandler;
        this.description = description;
        this.disposition = disposition;
        this.fileName = fileName;
        this.inputStream = inputStream;
        this.lineCount = lineCount;
        this.size = size;
    }
}
