// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * ServiceMgmtInputApi
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("ServiceMgmtInputApi")
@JsonPropertyOrder({
    "apiDefinition",
    "apiDescription",
    "apiName",
    "apiVersion",
    "authorizationValue",
    "maturityState",
    "rootFileName",
    "teams",
    "type",
    "url"
})
@Generated(value = "io.github.primelib.primecodegen")
public class ServiceMgmtInputApi {

    @JsonProperty("apiDefinition")
    protected ServiceMgmtApi apiDefinition;

    @JsonProperty("apiDescription")
    protected String apiDescription;

    @JsonProperty("apiName")
    protected String apiName;

    @JsonProperty("apiVersion")
    protected String apiVersion;

    @JsonProperty("authorizationValue")
    protected ServiceMgmtAuthorizationValue authorizationValue;

    @JsonProperty("maturityState")
    protected String maturityState;

    /**
     * Required when creating an API by importing protected URL
     */
    @JsonProperty("rootFileName")
    protected String rootFileName;

    /**
     * Contains teams to which the API must be assigned.
     */
    @JsonProperty("teams")
    protected List<ServiceMgmtTeam> teams;

    @JsonProperty("type")
    protected String type;

    /**
     * Required when creating an API by importing URL
     */
    @JsonProperty("url")
    protected String url;

    /**
     * Constructs a validated instance of {@link ServiceMgmtInputApi}.
     *
     * @param spec the specification to process
     */
    public ServiceMgmtInputApi(Consumer<ServiceMgmtInputApi> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link ServiceMgmtInputApi}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #ServiceMgmtInputApi(Consumer)} instead.
     * @param apiDefinition apiDefinition
     * @param apiDescription apiDescription
     * @param apiName apiName
     * @param apiVersion apiVersion
     * @param authorizationValue authorizationValue
     * @param maturityState maturityState
     * @param rootFileName Required when creating an API by importing protected URL
     * @param teams Contains teams to which the API must be assigned.
     * @param type type
     * @param url Required when creating an API by importing URL
     */
    @ApiStatus.Internal
    public ServiceMgmtInputApi(ServiceMgmtApi apiDefinition, String apiDescription, String apiName, String apiVersion, ServiceMgmtAuthorizationValue authorizationValue, String maturityState, String rootFileName, List<ServiceMgmtTeam> teams, String type, String url) {
        this.apiDefinition = apiDefinition;
        this.apiDescription = apiDescription;
        this.apiName = apiName;
        this.apiVersion = apiVersion;
        this.authorizationValue = authorizationValue;
        this.maturityState = maturityState;
        this.rootFileName = rootFileName;
        this.teams = teams;
        this.type = type;
        this.url = url;
    }
}
