// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Map;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * ServiceMgmtProperty
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("ServiceMgmtProperty")
@JsonPropertyOrder({
    "access",
    "allowEmptyValue",
    "description",
    "example",
    "format",
    "name",
    "nullable",
    "position",
    "readOnly",
    "required",
    "title",
    "type",
    "vendorExtensions",
    "xml"
})
@Generated(value = "io.github.primelib.primecodegen")
public class ServiceMgmtProperty {

    @JsonProperty("access")
    protected String access;

    @JsonProperty("allowEmptyValue")
    protected Boolean allowEmptyValue;

    @JsonProperty("description")
    protected String description;

    /**
     * A free-form property to include an example of an instance for this schema. To represent examples that cannot be naturally represented in JSON or YAML, a string value can be used to contain the example with escaping where necessary
     */
    @JsonProperty("example")
    protected Object example;

    @JsonProperty("format")
    protected String format;

    @JsonProperty("name")
    protected String name;

    @JsonProperty("nullable")
    protected Boolean nullable;

    @JsonProperty("position")
    protected Integer position;

    @JsonProperty("readOnly")
    protected Boolean readOnly;

    @JsonProperty("required")
    protected Boolean required;

    @JsonProperty("title")
    protected String title;

    @JsonProperty("type")
    protected String type;

    @JsonProperty("vendorExtensions")
    protected Map<String, Object> vendorExtensions;

    @JsonProperty("xml")
    protected ServiceMgmtXml xml;

    /**
     * Constructs a validated instance of {@link ServiceMgmtProperty}.
     *
     * @param spec the specification to process
     */
    public ServiceMgmtProperty(Consumer<ServiceMgmtProperty> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link ServiceMgmtProperty}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #ServiceMgmtProperty(Consumer)} instead.
     * @param access access
     * @param allowEmptyValue allowEmptyValue
     * @param description description
     * @param example A free-form property to include an example of an instance for this schema. To represent examples that cannot be naturally represented in JSON or YAML, a string value can be used to contain the example with escaping where necessary
     * @param format format
     * @param name name
     * @param nullable nullable
     * @param position position
     * @param readOnly readOnly
     * @param required required
     * @param title title
     * @param type type
     * @param vendorExtensions vendorExtensions
     * @param xml xml
     */
    @ApiStatus.Internal
    public ServiceMgmtProperty(String access, Boolean allowEmptyValue, String description, Object example, String format, String name, Boolean nullable, Integer position, Boolean readOnly, Boolean required, String title, String type, Map<String, Object> vendorExtensions, ServiceMgmtXml xml) {
        this.access = access;
        this.allowEmptyValue = allowEmptyValue;
        this.description = description;
        this.example = example;
        this.format = format;
        this.name = name;
        this.nullable = nullable;
        this.position = position;
        this.readOnly = readOnly;
        this.required = required;
        this.title = title;
        this.type = type;
        this.vendorExtensions = vendorExtensions;
        this.xml = xml;
    }
}
