// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * ServiceMgmtMockedConditionsBasedCustomResponse
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("ServiceMgmtMockedConditionsBasedCustomResponse")
@JsonPropertyOrder({
    "mockedConditionList",
    "mockedResponse"
})
@Generated(value = "io.github.primelib.primecodegen")
public class ServiceMgmtMockedConditionsBasedCustomResponse {

    @JsonProperty("mockedConditionList")
    protected List<ServiceMgmtMockedCondition> mockedConditionList;

    @JsonProperty("mockedResponse")
    protected ServiceMgmtMockedResponse mockedResponse;

    /**
     * Constructs a validated instance of {@link ServiceMgmtMockedConditionsBasedCustomResponse}.
     *
     * @param spec the specification to process
     */
    public ServiceMgmtMockedConditionsBasedCustomResponse(Consumer<ServiceMgmtMockedConditionsBasedCustomResponse> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link ServiceMgmtMockedConditionsBasedCustomResponse}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #ServiceMgmtMockedConditionsBasedCustomResponse(Consumer)} instead.
     * @param mockedConditionList mockedConditionList
     * @param mockedResponse mockedResponse
     */
    @ApiStatus.Internal
    public ServiceMgmtMockedConditionsBasedCustomResponse(List<ServiceMgmtMockedCondition> mockedConditionList, ServiceMgmtMockedResponse mockedResponse) {
        this.mockedConditionList = mockedConditionList;
        this.mockedResponse = mockedResponse;
    }
}
