// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * ServiceMgmtAPIAccessKey
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("ServiceMgmtAPIAccessKey")
@JsonPropertyOrder({
    "apiAccessKey",
    "expirationDate",
    "expirationInterval"
})
@Generated(value = "io.github.primelib.primecodegen")
public class ServiceMgmtAPIAccessKey {

    /**
     * API access key
     */
    @JsonProperty("apiAccessKey")
    protected String apiAccessKey;

    /**
     * expiration date of the api key
     */
    @JsonProperty("expirationDate")
    protected String expirationDate;

    /**
     * expiration interval of the api key
     */
    @JsonProperty("expirationInterval")
    protected String expirationInterval;

    /**
     * Constructs a validated instance of {@link ServiceMgmtAPIAccessKey}.
     *
     * @param spec the specification to process
     */
    public ServiceMgmtAPIAccessKey(Consumer<ServiceMgmtAPIAccessKey> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link ServiceMgmtAPIAccessKey}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #ServiceMgmtAPIAccessKey(Consumer)} instead.
     * @param apiAccessKey API access key
     * @param expirationDate expiration date of the api key
     * @param expirationInterval expiration interval of the api key
     */
    @ApiStatus.Internal
    public ServiceMgmtAPIAccessKey(String apiAccessKey, String expirationDate, String expirationInterval) {
        this.apiAccessKey = apiAccessKey;
        this.expirationDate = expirationDate;
        this.expirationInterval = expirationInterval;
    }
}
