// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * ServiceMgmtActionImport
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("ServiceMgmtActionImport")
@JsonPropertyOrder({
    "action",
    "enabled"
})
@Generated(value = "io.github.primelib.primecodegen")
public class ServiceMgmtActionImport {

    @JsonProperty("action")
    protected String action;

    @JsonProperty("enabled")
    protected Boolean enabled;

    /**
     * Constructs a validated instance of {@link ServiceMgmtActionImport}.
     *
     * @param spec the specification to process
     */
    public ServiceMgmtActionImport(Consumer<ServiceMgmtActionImport> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link ServiceMgmtActionImport}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #ServiceMgmtActionImport(Consumer)} instead.
     * @param action action
     * @param enabled enabled
     */
    @ApiStatus.Internal
    public ServiceMgmtActionImport(String action, Boolean enabled) {
        this.action = action;
        this.enabled = enabled;
    }
}
