// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * ServiceMgmtServiceRegistryUnpublishPutResponse
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("ServiceMgmtServiceRegistryUnpublishPutResponse")
@JsonPropertyOrder({
    "unpublishResponse",
    "unpublishResponses"
})
@Generated(value = "io.github.primelib.primecodegen")
public class ServiceMgmtServiceRegistryUnpublishPutResponse {

    @JsonProperty("unpublishResponse")
    protected ServiceMgmtUnpublishResponse unpublishResponse;

    /**
     * This contains the service registry unpublish status for requests unpublishing more than one API from one or more service registries.
     */
    @JsonProperty("unpublishResponses")
    protected List<ServiceMgmtUnpublishResponse> unpublishResponses;

    /**
     * Constructs a validated instance of {@link ServiceMgmtServiceRegistryUnpublishPutResponse}.
     *
     * @param spec the specification to process
     */
    public ServiceMgmtServiceRegistryUnpublishPutResponse(Consumer<ServiceMgmtServiceRegistryUnpublishPutResponse> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link ServiceMgmtServiceRegistryUnpublishPutResponse}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #ServiceMgmtServiceRegistryUnpublishPutResponse(Consumer)} instead.
     * @param unpublishResponse unpublishResponse
     * @param unpublishResponses This contains the service registry unpublish status for requests unpublishing more than one API from one or more service registries.
     */
    @ApiStatus.Internal
    public ServiceMgmtServiceRegistryUnpublishPutResponse(ServiceMgmtUnpublishResponse unpublishResponse, List<ServiceMgmtUnpublishResponse> unpublishResponses) {
        this.unpublishResponse = unpublishResponse;
        this.unpublishResponses = unpublishResponses;
    }
}
