// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * ServiceMgmtInputVersion
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("ServiceMgmtInputVersion")
@JsonPropertyOrder({
    "newApiVersion",
    "retainApplications"
})
@Generated(value = "io.github.primelib.primecodegen")
public class ServiceMgmtInputVersion {

    @JsonProperty("newApiVersion")
    protected String newApiVersion;

    @JsonProperty("retainApplications")
    protected Boolean retainApplications;

    /**
     * Constructs a validated instance of {@link ServiceMgmtInputVersion}.
     *
     * @param spec the specification to process
     */
    public ServiceMgmtInputVersion(Consumer<ServiceMgmtInputVersion> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link ServiceMgmtInputVersion}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #ServiceMgmtInputVersion(Consumer)} instead.
     * @param newApiVersion newApiVersion
     * @param retainApplications retainApplications
     */
    @ApiStatus.Internal
    public ServiceMgmtInputVersion(String newApiVersion, Boolean retainApplications) {
        this.newApiVersion = newApiVersion;
        this.retainApplications = retainApplications;
    }
}
