// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * ServiceMgmtGqlFieldDefinition
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("ServiceMgmtGqlFieldDefinition")
@JsonPropertyOrder({
    "comments",
    "description",
    "directives",
    "directivesByName",
    "enabled",
    "inputValueDefinitions",
    "name",
    "type"
})
@Generated(value = "io.github.primelib.primecodegen")
public class ServiceMgmtGqlFieldDefinition {

    /**
     * List of comments
     */
    @JsonProperty("comments")
    protected List<ServiceMgmtGqlComment> comments;

    @JsonProperty("description")
    protected ServiceMgmtGqlDescription description;

    /**
     * List of directives
     */
    @JsonProperty("directives")
    protected List<ServiceMgmtGqlDirective> directives;

    @JsonProperty("directivesByName")
    protected Map<String, ServiceMgmtGqlDirective> directivesByName;

    /**
     * Flag to specify if this field is enabled or not
     */
    @JsonProperty("enabled")
    protected Boolean enabled;

    /**
     * List of input value type definitions
     */
    @JsonProperty("inputValueDefinitions")
    protected List<ServiceMgmtGqlInputValueDefinition> inputValueDefinitions;

    /**
     * Name of the field definition
     */
    @JsonProperty("name")
    protected String name;

    @JsonProperty("type")
    protected ServiceMgmtGqlType type;

    /**
     * Constructs a validated instance of {@link ServiceMgmtGqlFieldDefinition}.
     *
     * @param spec the specification to process
     */
    public ServiceMgmtGqlFieldDefinition(Consumer<ServiceMgmtGqlFieldDefinition> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link ServiceMgmtGqlFieldDefinition}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #ServiceMgmtGqlFieldDefinition(Consumer)} instead.
     * @param comments List of comments
     * @param description description
     * @param directives List of directives
     * @param directivesByName directivesByName
     * @param enabled Flag to specify if this field is enabled or not
     * @param inputValueDefinitions List of input value type definitions
     * @param name Name of the field definition
     * @param type type
     */
    @ApiStatus.Internal
    public ServiceMgmtGqlFieldDefinition(List<ServiceMgmtGqlComment> comments, ServiceMgmtGqlDescription description, List<ServiceMgmtGqlDirective> directives, Map<String, ServiceMgmtGqlDirective> directivesByName, Boolean enabled, List<ServiceMgmtGqlInputValueDefinition> inputValueDefinitions, String name, ServiceMgmtGqlType type) {
        this.comments = comments;
        this.description = description;
        this.directives = directives;
        this.directivesByName = directivesByName;
        this.enabled = enabled;
        this.inputValueDefinitions = inputValueDefinitions;
        this.name = name;
        this.type = type;
    }
}
