// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * ServiceMgmtTransactionEventObject
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("ServiceMgmtTransactionEventObject")
@JsonPropertyOrder({
    "correlationId",
    "creationDate",
    "status",
    "statusCode"
})
@Generated(value = "io.github.primelib.primecodegen")
public class ServiceMgmtTransactionEventObject {

    /**
     * The correlation ID of the event which uniquely identifies an API invocation.
     */
    @JsonProperty("correlationID")
    protected String correlationId;

    /**
     * The epoch start timestamp of the event in milliseconds.
     */
    @JsonProperty("creationDate")
    protected Long creationDate;

    /**
     * The execution status of the event. Indicated as SUCCESS or FAILURE.
     */
    @JsonProperty("status")
    protected String status;

    /**
     * The HTTP status returned in the response for the API invocation.
     */
    @JsonProperty("statusCode")
    protected Integer statusCode;

    /**
     * Constructs a validated instance of {@link ServiceMgmtTransactionEventObject}.
     *
     * @param spec the specification to process
     */
    public ServiceMgmtTransactionEventObject(Consumer<ServiceMgmtTransactionEventObject> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link ServiceMgmtTransactionEventObject}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #ServiceMgmtTransactionEventObject(Consumer)} instead.
     * @param correlationId The correlation ID of the event which uniquely identifies an API invocation.
     * @param creationDate The epoch start timestamp of the event in milliseconds.
     * @param status The execution status of the event. Indicated as SUCCESS or FAILURE.
     * @param statusCode The HTTP status returned in the response for the API invocation.
     */
    @ApiStatus.Internal
    public ServiceMgmtTransactionEventObject(String correlationId, Long creationDate, String status, Integer statusCode) {
        this.correlationId = correlationId;
        this.creationDate = creationDate;
        this.status = status;
        this.statusCode = statusCode;
    }
}
