// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.Map;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * ServiceMgmtMockedResponse
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("ServiceMgmtMockedResponse")
@JsonPropertyOrder({
    "responseBody",
    "responseHeaders",
    "statusCode"
})
@Generated(value = "io.github.primelib.primecodegen")
public class ServiceMgmtMockedResponse {

    @JsonProperty("responseBody")
    protected Map<String, Object> responseBody;

    /**
     * Outgoing response headers
     */
    @JsonProperty("responseHeaders")
    protected Map<String, String> responseHeaders;

    @JsonProperty("statusCode")
    protected String statusCode;

    /**
     * Constructs a validated instance of {@link ServiceMgmtMockedResponse}.
     *
     * @param spec the specification to process
     */
    public ServiceMgmtMockedResponse(Consumer<ServiceMgmtMockedResponse> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link ServiceMgmtMockedResponse}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #ServiceMgmtMockedResponse(Consumer)} instead.
     * @param responseBody responseBody
     * @param responseHeaders Outgoing response headers
     * @param statusCode statusCode
     */
    @ApiStatus.Internal
    public ServiceMgmtMockedResponse(Map<String, Object> responseBody, Map<String, String> responseHeaders, String statusCode) {
        this.responseBody = responseBody;
        this.responseHeaders = responseHeaders;
        this.statusCode = statusCode;
    }
}
