// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * ServiceMgmtSoapoperation
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("ServiceMgmtSoapoperation")
@JsonPropertyOrder({
    "bindings",
    "defined",
    "enabled",
    "headers",
    "isRestinvokeEnabled",
    "mockedConditionsBasedCustomResponsesList",
    "mockedResponses",
    "name",
    "namespace",
    "restEnabledPath",
    "scopes",
    "soapAction",
    "tags"
})
@Generated(value = "io.github.primelib.primecodegen")
public class ServiceMgmtSoapoperation {

    @JsonProperty("bindings")
    protected List<ServiceMgmtSoapbinding> bindings;

    @JsonProperty("defined")
    protected Boolean defined;

    @JsonProperty("enabled")
    protected Boolean enabled;

    @JsonProperty("headers")
    protected List<String> headers;

    @JsonProperty("isRESTInvokeEnabled")
    protected Boolean isRestinvokeEnabled;

    @JsonProperty("mockedConditionsBasedCustomResponsesList")
    protected List<ServiceMgmtMockedConditionsBasedCustomResponse> mockedConditionsBasedCustomResponsesList;

    @JsonProperty("mockedResponses")
    protected Map<String, ServiceMgmtMockedResponse> mockedResponses;

    @JsonProperty("name")
    protected String name;

    @JsonProperty("namespace")
    protected String namespace;

    @JsonProperty("restEnabledPath")
    protected ServiceMgmtRestEnabledPath restEnabledPath;

    @JsonProperty("scopes")
    protected List<String> scopes;

    @JsonProperty("soapAction")
    protected String soapAction;

    @JsonProperty("tags")
    protected List<String> tags;

    /**
     * Constructs a validated instance of {@link ServiceMgmtSoapoperation}.
     *
     * @param spec the specification to process
     */
    public ServiceMgmtSoapoperation(Consumer<ServiceMgmtSoapoperation> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link ServiceMgmtSoapoperation}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #ServiceMgmtSoapoperation(Consumer)} instead.
     * @param bindings bindings
     * @param defined defined
     * @param enabled enabled
     * @param headers headers
     * @param isRestinvokeEnabled isRestinvokeEnabled
     * @param mockedConditionsBasedCustomResponsesList mockedConditionsBasedCustomResponsesList
     * @param mockedResponses mockedResponses
     * @param name name
     * @param namespace namespace
     * @param restEnabledPath restEnabledPath
     * @param scopes scopes
     * @param soapAction soapAction
     * @param tags tags
     */
    @ApiStatus.Internal
    public ServiceMgmtSoapoperation(List<ServiceMgmtSoapbinding> bindings, Boolean defined, Boolean enabled, List<String> headers, Boolean isRestinvokeEnabled, List<ServiceMgmtMockedConditionsBasedCustomResponse> mockedConditionsBasedCustomResponsesList, Map<String, ServiceMgmtMockedResponse> mockedResponses, String name, String namespace, ServiceMgmtRestEnabledPath restEnabledPath, List<String> scopes, String soapAction, List<String> tags) {
        this.bindings = bindings;
        this.defined = defined;
        this.enabled = enabled;
        this.headers = headers;
        this.isRestinvokeEnabled = isRestinvokeEnabled;
        this.mockedConditionsBasedCustomResponsesList = mockedConditionsBasedCustomResponsesList;
        this.mockedResponses = mockedResponses;
        this.name = name;
        this.namespace = namespace;
        this.restEnabledPath = restEnabledPath;
        this.scopes = scopes;
        this.soapAction = soapAction;
        this.tags = tags;
    }
}
