// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * ServiceMgmtRestEnabledPath
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("ServiceMgmtRestEnabledPath")
@JsonPropertyOrder({
    "delete",
    "description",
    "displayName",
    "enabled",
    "get",
    "getref",
    "head",
    "invokePath",
    "name",
    "options",
    "parameters",
    "patch",
    "post",
    "put",
    "scopes",
    "summary",
    "tags",
    "trace",
    "vendorExtensions"
})
@Generated(value = "io.github.primelib.primecodegen")
public class ServiceMgmtRestEnabledPath {

    @JsonProperty("delete")
    protected ServiceMgmtOperation delete;

    /**
     * An optional, string description, intended to apply to all operations in this path
     */
    @JsonProperty("description")
    protected String description;

    @JsonProperty("displayName")
    protected String displayName;

    @JsonProperty("enabled")
    protected Boolean enabled;

    @JsonProperty("get")
    protected ServiceMgmtOperation get;

    /**
     * Allows for an external definition of this path item
     */
    @JsonProperty("get$ref")
    protected String getref;

    @JsonProperty("head")
    protected ServiceMgmtOperation head;

    @JsonProperty("invokePath")
    protected String invokePath;

    @JsonProperty("name")
    protected String name;

    @JsonProperty("options")
    protected ServiceMgmtOperation options;

    /**
     * A list of parameters that are applicable for all the operations described under this path. These parameters can be overridden at the operation level, but cannot be removed there
     */
    @JsonProperty("parameters")
    protected List<Object> parameters;

    @JsonProperty("patch")
    protected ServiceMgmtOperation patch;

    @JsonProperty("post")
    protected ServiceMgmtOperation post;

    @JsonProperty("put")
    protected ServiceMgmtOperation put;

    @JsonProperty("scopes")
    protected List<String> scopes;

    /**
     * An optional, string summary, intended to apply to all operations in this path
     */
    @JsonProperty("summary")
    protected String summary;

    @JsonProperty("tags")
    protected List<String> tags;

    @JsonProperty("trace")
    protected ServiceMgmtOperation trace;

    @JsonProperty("vendorExtensions")
    protected Map<String, Object> vendorExtensions;

    /**
     * Constructs a validated instance of {@link ServiceMgmtRestEnabledPath}.
     *
     * @param spec the specification to process
     */
    public ServiceMgmtRestEnabledPath(Consumer<ServiceMgmtRestEnabledPath> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link ServiceMgmtRestEnabledPath}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #ServiceMgmtRestEnabledPath(Consumer)} instead.
     * @param delete delete
     * @param description An optional, string description, intended to apply to all operations in this path
     * @param displayName displayName
     * @param enabled enabled
     * @param get get
     * @param getref Allows for an external definition of this path item
     * @param head head
     * @param invokePath invokePath
     * @param name name
     * @param options options
     * @param parameters A list of parameters that are applicable for all the operations described under this path. These parameters can be overridden at the operation level, but cannot be removed there
     * @param patch patch
     * @param post post
     * @param put put
     * @param scopes scopes
     * @param summary An optional, string summary, intended to apply to all operations in this path
     * @param tags tags
     * @param trace trace
     * @param vendorExtensions vendorExtensions
     */
    @ApiStatus.Internal
    public ServiceMgmtRestEnabledPath(ServiceMgmtOperation delete, String description, String displayName, Boolean enabled, ServiceMgmtOperation get, String getref, ServiceMgmtOperation head, String invokePath, String name, ServiceMgmtOperation options, List<Object> parameters, ServiceMgmtOperation patch, ServiceMgmtOperation post, ServiceMgmtOperation put, List<String> scopes, String summary, List<String> tags, ServiceMgmtOperation trace, Map<String, Object> vendorExtensions) {
        this.delete = delete;
        this.description = description;
        this.displayName = displayName;
        this.enabled = enabled;
        this.get = get;
        this.getref = getref;
        this.head = head;
        this.invokePath = invokePath;
        this.name = name;
        this.options = options;
        this.parameters = parameters;
        this.patch = patch;
        this.post = post;
        this.put = put;
        this.scopes = scopes;
        this.summary = summary;
        this.tags = tags;
        this.trace = trace;
        this.vendorExtensions = vendorExtensions;
    }
}
