// WARNING: This file was generated by PrimeCodeGen. DO NOT EDIT.

package io.github.primelib.webmethodsapigateway4j.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.function.Consumer;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;
import org.jetbrains.annotations.ApiStatus;

/**
 * UserMgmtUnlockAccounts
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@JsonTypeName("UserMgmtUnlockAccounts")
@JsonPropertyOrder({
    "userName"
})
@Generated(value = "io.github.primelib.primecodegen")
public class UserMgmtUnlockAccounts {

    /**
     * Username that needs to be unlocked.
     */
    @JsonProperty("userName")
    protected List<String> userName;

    /**
     * Constructs a validated instance of {@link UserMgmtUnlockAccounts}.
     *
     * @param spec the specification to process
     */
    public UserMgmtUnlockAccounts(Consumer<UserMgmtUnlockAccounts> spec) {
        super();
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link UserMgmtUnlockAccounts}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #UserMgmtUnlockAccounts(Consumer)} instead.
     * @param userName Username that needs to be unlocked.
     */
    @ApiStatus.Internal
    public UserMgmtUnlockAccounts(List<String> userName) {
        this.userName = userName;
    }
}
