package io.github.primelib.webmethodsapigateway4j.model;

import java.util.function.Consumer;
import org.jetbrains.annotations.ApiStatus;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

import java.util.List;
import java.util.Map;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ModelPackage
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@Builder
@JsonPropertyOrder({
    "active",
    "apiIds",
    "creationDate",
    "customFields",
    "description",
    "icon",
    "id",
    "modifiedDate",
    "name",
    "planIds",
    "policyIds",
    "publishedPortals",
    "tags",
    "version"
})
@JsonTypeName("Package")
@Generated(value = "io.github.primelib.primecodegen.javafeign.JavaFeignGenerator")
public class ModelPackage {

    @JsonProperty("active")
    protected Boolean active;

    /**
     * List of api ids needs to be associated to package. It can be either provided during the package creation or separately using package update call
     */
    @JsonProperty("apiIds")
    protected Set<String> apiIds;

    /**
     * The creation date of package in milli seconds
     */
    @JsonProperty("creationDate")
    protected Long creationDate;

    /**
     * This can be used to store additional information needed for a package
     */
    @JsonProperty("customFields")
    protected Map<String, Object> customFields;

    /**
     * Description of the package
     */
    @JsonProperty("description")
    protected String description;

    /**
     * An inline base64 encoded string representation of icon to be used in package
     */
    @JsonProperty("icon")
    protected String icon;

    /**
     * Id of the package. It will be autogenerated for the package on creation
     */
    @JsonProperty("id")
    protected String id;

    /**
     * The modified date of package in milli seconds. This will be updated for package on update, hot edit, activate and deactivate.
     */
    @JsonProperty("modifiedDate")
    protected Long modifiedDate;

    /**
     * Name of the package
     */
    @JsonProperty("name")
    protected String name;

    /**
     * List of plan ids needs to be associated to the package. It can be either provided during the package creation or separately using package update call
     */
    @JsonProperty("planIds")
    protected Set<String> planIds;

    /**
     * Policy id that contains the IAM policy to use for APIs associated to package. It will be created automatically.
     */
    @JsonProperty("policyIds")
    protected List<String> policyIds;

    /**
     * List of published portal ids of the package.
     */
    @JsonProperty("publishedPortals")
    protected List<String> publishedPortals;

    /**
     * List of tags of the package. Either it can provided during the creation of the package or separately using the package update call
     */
    @JsonProperty("tags")
    protected List<String> tags;

    /**
     * Version of the package created
     */
    @JsonProperty("version")
    protected String version;

    /**
     * Constructs a validated instance of {@link ModelPackage}.
     *
     * @param spec the specification to process
     */
    public ModelPackage(Consumer<ModelPackage> spec) {
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link ModelPackage}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #ModelPackage(Consumer)} instead.
     * @param active active
     * @param apiIds List of api ids needs to be associated to package. It can be either provided during the package creation or separately using package update call
     * @param creationDate The creation date of package in milli seconds
     * @param customFields This can be used to store additional information needed for a package
     * @param description Description of the package
     * @param icon An inline base64 encoded string representation of icon to be used in package
     * @param id Id of the package. It will be autogenerated for the package on creation
     * @param modifiedDate The modified date of package in milli seconds. This will be updated for package on update, hot edit, activate and deactivate.
     * @param name Name of the package
     * @param planIds List of plan ids needs to be associated to the package. It can be either provided during the package creation or separately using package update call
     * @param policyIds Policy id that contains the IAM policy to use for APIs associated to package. It will be created automatically.
     * @param publishedPortals List of published portal ids of the package.
     * @param tags List of tags of the package. Either it can provided during the creation of the package or separately using the package update call
     * @param version Version of the package created
     */
    @ApiStatus.Internal
    public ModelPackage(Boolean active, Set<String> apiIds, Long creationDate, Map<String, Object> customFields, String description, String icon, String id, Long modifiedDate, String name, Set<String> planIds, List<String> policyIds, List<String> publishedPortals, List<String> tags, String version) {
        this.active = active;
        this.apiIds = apiIds;
        this.creationDate = creationDate;
        this.customFields = customFields;
        this.description = description;
        this.icon = icon;
        this.id = id;
        this.modifiedDate = modifiedDate;
        this.name = name;
        this.planIds = planIds;
        this.policyIds = policyIds;
        this.publishedPortals = publishedPortals;
        this.tags = tags;
        this.version = version;
    }

}
