package io.github.primelib.webmethodsapigateway4j.model;

import java.util.function.Consumer;
import org.jetbrains.annotations.ApiStatus;
import javax.annotation.processing.Generated;
import lombok.AccessLevel;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import lombok.NoArgsConstructor;
import lombok.experimental.Accessors;

import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Plan
 *
 */
@Getter
@Setter
@EqualsAndHashCode
@ToString
@Accessors(fluent = true, chain = true)
@NoArgsConstructor(access = AccessLevel.PROTECTED, force = true)
@Builder
@JsonPropertyOrder({
    "License",
    "Terms",
    "cost",
    "creationDate",
    "customFields",
    "description",
    "icon",
    "id",
    "modifiedDate",
    "name",
    "policies",
    "protected",
    "quota",
    "tags",
    "version"
})
@JsonTypeName("Plan")
@Generated(value = "io.github.primelib.primecodegen.javafeign.JavaFeignGenerator")
public class Plan {

    /**
     * License of the plan
     */
    @JsonProperty("License")
    protected String license;

    /**
     * Terms of the plan usage as descriptive string
     */
    @JsonProperty("Terms")
    protected String terms;

    @JsonProperty("cost")
    protected Cost cost;

    /**
     * The creation date of plan in milli seconds
     */
    @JsonProperty("creationDate")
    protected Long creationDate;

    /**
     * This can be used to store additional information needed for a plan
     */
    @JsonProperty("customFields")
    protected Map<String, Object> customFields;

    /**
     * Description of the plan
     */
    @JsonProperty("description")
    protected String description;

    /**
     * An inline base64 encoded string representation of icon to be used in plan
     */
    @JsonProperty("icon")
    protected String icon;

    /**
     * Id of the plan. It will be autogenerated for the plan on creation
     */
    @JsonProperty("id")
    protected String id;

    /**
     * The modified date of plan in milli seconds. This will be updated for plan on update.
     */
    @JsonProperty("modifiedDate")
    protected Long modifiedDate;

    /**
     * Name of the plan
     */
    @JsonProperty("name")
    protected String name;

    /**
     * Policy that holds the rate limit throttling policy actions. It will created automatically. It can contain zero or more throttling policy action as rate limit policy
     */
    @JsonProperty("policies")
    protected List<String> policies;

    @JsonProperty("protected")
    protected Boolean _protected;

    @JsonProperty("quota")
    protected Quota quota;

    /**
     * List of tags of the plan
     */
    @JsonProperty("tags")
    protected List<String> tags;

    /**
     * Version of the plan
     */
    @JsonProperty("version")
    protected String version;

    /**
     * Constructs a validated instance of {@link Plan}.
     *
     * @param spec the specification to process
     */
    public Plan(Consumer<Plan> spec) {
        spec.accept(this);
    }

    /**
     * Constructs a validated instance of {@link Plan}.
     * <p>
     * NOTE: This constructor is not considered stable and may change if the model is updated. Consider using {@link #Plan(Consumer)} instead.
     * @param license License of the plan
     * @param terms Terms of the plan usage as descriptive string
     * @param cost cost
     * @param creationDate The creation date of plan in milli seconds
     * @param customFields This can be used to store additional information needed for a plan
     * @param description Description of the plan
     * @param icon An inline base64 encoded string representation of icon to be used in plan
     * @param id Id of the plan. It will be autogenerated for the plan on creation
     * @param modifiedDate The modified date of plan in milli seconds. This will be updated for plan on update.
     * @param name Name of the plan
     * @param policies Policy that holds the rate limit throttling policy actions. It will created automatically. It can contain zero or more throttling policy action as rate limit policy
     * @param _protected _protected
     * @param quota quota
     * @param tags List of tags of the plan
     * @param version Version of the plan
     */
    @ApiStatus.Internal
    public Plan(String license, String terms, Cost cost, Long creationDate, Map<String, Object> customFields, String description, String icon, String id, Long modifiedDate, String name, List<String> policies, Boolean _protected, Quota quota, List<String> tags, String version) {
        this.license = license;
        this.terms = terms;
        this.cost = cost;
        this.creationDate = creationDate;
        this.customFields = customFields;
        this.description = description;
        this.icon = icon;
        this.id = id;
        this.modifiedDate = modifiedDate;
        this.name = name;
        this.policies = policies;
        this._protected = _protected;
        this.quota = quota;
        this.tags = tags;
        this.version = version;
    }

}
